/* Generated by tools/gen_latin_supplement.py - DO NOT EDIT BY HAND.
 * Font: Montserrat-Medium.ttf   Size: 10 px   Bpp: 4   Glyphs: ±ÄÖ×Üßäöü–“”„
 *
 * ---------------------------------------------------------------------
 * Derived from the Montserrat typeface.
 *   Copyright 2011 The Montserrat Project Authors
 *   https://github.com/JulietaUla/Montserrat
 *
 * Licensed under the SIL Open Font License, Version 1.1.
 *   https://scripts.sil.org/OFL
 *
 * The OFL treats a conversion to another format as a Modified Version,
 * so this file is itself Font Software and stays under the OFL. It may
 * be redistributed only together with this notice and the licence text
 * (see THIRD-PARTY-NOTICES.md), and not under the reserved name
 * "Montserrat".
 * ---------------------------------------------------------------------
 */
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#ifndef LATIN_SUPPL_10
#define LATIN_SUPPL_10 1
#endif

#if LATIN_SUPPL_10

/*-----------------
 *    BITMAPS
 *----------------*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0x00, 0x85, 0x00, 0x00, 0x85, 0x00, 0x5e, 0xfe, 0xe2, 0x00, 0x85, 0x00,
    0x00, 0x85, 0x00, 0x00, 0x00, 0x00, 0x5e, 0xee, 0xe2, 0x00, 0x09, 0x2a,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xf5, 0x00, 0x00, 0x00,
    0x7b, 0xb0, 0x00, 0x00, 0x0c, 0x2c, 0x20, 0x00, 0x04, 0xb0, 0x78, 0x00,
    0x00, 0x95, 0x01, 0xd0, 0x00, 0x1e, 0xee, 0xef, 0x50, 0x06, 0x90, 0x00,
    0x4b, 0x00, 0xc3, 0x00, 0x00, 0xd2, 0x00, 0x28, 0x37, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x8d, 0xeb, 0x30, 0x0a, 0x91, 0x05, 0xe2, 0x3c, 0x00,
    0x00, 0x7a, 0x78, 0x00, 0x00, 0x2d, 0x78, 0x00, 0x00, 0x2d, 0x4c, 0x00,
    0x00, 0x7a, 0x0b, 0x91, 0x05, 0xe2, 0x00, 0x8e, 0xeb, 0x30, 0x20, 0x02,
    0x97, 0xa6, 0x0d, 0xb0, 0x97, 0xa6, 0x20, 0x02, 0x00, 0x55, 0x73, 0x00,
    0x00, 0x00, 0x00, 0x0f, 0x00, 0x01, 0xe0, 0xf0, 0x00, 0x1e, 0x0f, 0x00,
    0x01, 0xe0, 0xf0, 0x00, 0x1e, 0x0f, 0x00, 0x01, 0xd0, 0xd2, 0x00, 0x3c,
    0x08, 0x91, 0x1b, 0x70, 0x19, 0xed, 0x80, 0x03, 0xce, 0xc2, 0x00, 0xd4,
    0x06, 0xa0, 0x1e, 0x00, 0x77, 0x01, 0xd0, 0xcf, 0x50, 0x1d, 0x00, 0x2d,
    0x21, 0xd0, 0x00, 0xa4, 0x1d, 0x00, 0x2d, 0x21, 0xd2, 0xee, 0x60, 0x05,
    0x57, 0x30, 0x00, 0x00, 0x00, 0x1a, 0xed, 0x50, 0x03, 0x02, 0xd0, 0x1b,
    0xee, 0xf1, 0x6a, 0x00, 0xd2, 0x6a, 0x04, 0xf2, 0x1b, 0xea, 0xc2, 0x02,
    0x84, 0x60, 0x00, 0x00, 0x00, 0x06, 0xde, 0x91, 0x3d, 0x20, 0xa8, 0x87,
    0x00, 0x2d, 0x87, 0x00, 0x2d, 0x3d, 0x21, 0xa8, 0x06, 0xde, 0x91, 0x00,
    0xa2, 0x90, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x2d, 0x2c, 0x00, 0x2d, 0x2c,
    0x00, 0x2d, 0x2d, 0x00, 0x2d, 0x0e, 0x30, 0x9d, 0x05, 0xdd, 0x8d, 0xee,
    0xee, 0xe0, 0x19, 0x28, 0x58, 0x76, 0x6a, 0x88, 0x6a, 0x78, 0x3a, 0x58,
    0x55, 0x73, 0x6a, 0x78, 0x39, 0x58, 0x55, 0x73,
};

/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 96, .box_w = 6, .box_h = 7, .ofs_x = 0, .ofs_y = 0}, /* U+00B1 '±' */
    {.bitmap_index = 21, .adv_w = 112, .box_w = 9, .box_h = 10, .ofs_x = -1, .ofs_y = 0}, /* U+00C4 'Ä' */
    {.bitmap_index = 66, .adv_w = 128, .box_w = 8, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00D6 'Ö' */
    {.bitmap_index = 106, .adv_w = 96, .box_w = 4, .box_h = 5, .ofs_x = 1, .ofs_y = 1}, /* U+00D7 '×' */
    {.bitmap_index = 116, .adv_w = 128, .box_w = 7, .box_h = 10, .ofs_x = 0, .ofs_y = 0}, /* U+00DC 'Ü' */
    {.bitmap_index = 151, .adv_w = 112, .box_w = 7, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+00DF 'ß' */
    {.bitmap_index = 179, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+00E4 'ä' */
    {.bitmap_index = 203, .adv_w = 96, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+00F6 'ö' */
    {.bitmap_index = 227, .adv_w = 112, .box_w = 6, .box_h = 8, .ofs_x = 0, .ofs_y = 0}, /* U+00FC 'ü' */
    {.bitmap_index = 251, .adv_w = 80, .box_w = 5, .box_h = 1, .ofs_x = 0, .ofs_y = 3}, /* U+2013 '–' */
    {.bitmap_index = 254, .adv_w = 64, .box_w = 4, .box_h = 3, .ofs_x = 0, .ofs_y = 5}, /* U+201C '“' */
    {.bitmap_index = 260, .adv_w = 64, .box_w = 4, .box_h = 3, .ofs_x = 0, .ofs_y = 5}, /* U+201D '”' */
    {.bitmap_index = 266, .adv_w = 64, .box_w = 4, .box_h = 3, .ofs_x = 0, .ofs_y = -2}, /* U+201E '„' */
};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/
static const uint16_t unicode_list_0[] = {
    0, 19, 37, 38, 43, 46, 51, 69, 75, 8034, 8043, 8044, 8045
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 177, .range_length = 8046, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL,
        .list_length = 13, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/
#if LV_VERSION_CHECK(8, 0, 0)
static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
};

/*-----------------
 *  PUBLIC FONT
 *----------------*/
#if LV_VERSION_CHECK(8, 0, 0)
const lv_font_t latin_suppl_10 = {
#else
lv_font_t latin_suppl_10 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 13,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};

#endif /* LATIN_SUPPL_10 */
