// Generated by tools/gen_latin_supplement.py - DO NOT EDIT BY HAND.
//
// Fallback fonts supplying the glyphs LVGL's built-in Montserrat fonts lack
// (umlauts, sharp-s, en dash, typographic quotes, plus-minus, multiplication).
// Chained onto the built-ins via lv_font_t.fallback in Theme.cpp.
//
// Derived from the Montserrat typeface, Copyright 2011 The Montserrat
// Project Authors, SIL Open Font License 1.1 - see the individual .c files.
#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t latin_suppl_10;
extern const lv_font_t latin_suppl_12;
extern const lv_font_t latin_suppl_14;
extern const lv_font_t latin_suppl_16;
extern const lv_font_t latin_suppl_18;
extern const lv_font_t latin_suppl_20;
extern const lv_font_t latin_suppl_22;
extern const lv_font_t latin_suppl_24;
extern const lv_font_t latin_suppl_28;
extern const lv_font_t latin_suppl_32;
extern const lv_font_t latin_suppl_36;
extern const lv_font_t latin_suppl_40;
extern const lv_font_t latin_suppl_44;
extern const lv_font_t latin_suppl_48;

#ifdef __cplusplus
}
#endif
