/* GENERATED by tools/gen_icons.py - DO NOT EDIT; run  python tools/gen_icons.py
 * OpenBridge icon trial: this file belongs to the trial (see ICONS-TRIAL.md).
 *
 * Code points of the OpenBridge icons in the Private Use Area, as UTF-8 string
 * literals, and the icon fonts. This header holds no artwork (MIT); the glyphs are
 * in ob_icons_<px>.c (CC BY 4.0).
 *
 * Each macro is ONE string literal of three \xNN escapes. Hex escapes are greedy,
 * so never glue a hex digit directly onto one inside the same literal: write
 * OB_ICON_ALARM " 5 m" (two literals), never "\xEE\x80\x96" "5" merged by hand.
 */
#pragma once
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#define OB_ICON_WIND           "\xEE\x80\x80"   /* U+E000 wind */
#define OB_ICON_STW            "\xEE\x80\x81"   /* U+E001 stw */
#define OB_ICON_DEPTH          "\xEE\x80\x82"   /* U+E002 depth */
#define OB_ICON_ENGINE         "\xEE\x80\x83"   /* U+E003 engine */
#define OB_ICON_RUDDER         "\xEE\x80\x84"   /* U+E004 propulsion-rudder */
#define OB_ICON_AIS            "\xEE\x80\x85"   /* U+E005 ais-target-activated-iec */
#define OB_ICON_TREND          "\xEE\x80\x86"   /* U+E006 trend */
#define OB_ICON_AUTOPILOT      "\xEE\x80\x87"   /* U+E007 command-autopilot */
#define OB_ICON_SOUND          "\xEE\x80\x88"   /* U+E008 sound */
#define OB_ICON_ROLL           "\xEE\x80\x89"   /* U+E009 roll */
#define OB_ICON_ANCHORWATCH    "\xEE\x80\x8A"   /* U+E00A anchorwatch */
#define OB_ICON_TANK           "\xEE\x80\x8B"   /* U+E00B tank */
#define OB_ICON_BATTERY        "\xEE\x80\x8C"   /* U+E00C battery-vertical-full */
#define OB_ICON_WEATHER        "\xEE\x80\x8D"   /* U+E00D weather */
#define OB_ICON_TIME           "\xEE\x80\x8E"   /* U+E00E time */
#define OB_ICON_WAYPOINT_NEXT  "\xEE\x80\x8F"   /* U+E00F waypoint-next-iec */
#define OB_ICON_TABLE          "\xEE\x80\x90"   /* U+E010 table */
#define OB_ICON_SETTINGS       "\xEE\x80\x91"   /* U+E011 settings-iec */
#define OB_ICON_HOME           "\xEE\x80\x92"   /* U+E012 home */
#define OB_ICON_CHEVRON_LEFT   "\xEE\x80\x93"   /* U+E013 chevron-left-google */
#define OB_ICON_CHEVRON_RIGHT  "\xEE\x80\x94"   /* U+E014 chevron-right-google */
#define OB_ICON_CLOSE          "\xEE\x80\x95"   /* U+E015 close-google */
#define OB_ICON_ALARM          "\xEE\x80\x96"   /* U+E016 alarm */
#define OB_ICON_SIMULATION     "\xEE\x80\x97"   /* U+E017 simulation */
#define OB_ICON_MEDIA_PREV     "\xEE\x80\x98"   /* U+E018 media-skip-previous */
#define OB_ICON_MEDIA_PLAY     "\xEE\x80\x99"   /* U+E019 media-play */
#define OB_ICON_MEDIA_PAUSE    "\xEE\x80\x9A"   /* U+E01A media-pause */
#define OB_ICON_MEDIA_NEXT     "\xEE\x80\x9B"   /* U+E01B media-skip-next */
#define OB_ICON_SOUND_MUTED    "\xEE\x80\x9C"   /* U+E01C sound-muted */

#define OB_ICON_COUNT 29

/* Icon font sizes compiled into this board (pixel sizes of the font roles). */
#if defined(BOARD_PANEL_1024X600)
#define OB_ICON_SIZES(X) X(12) X(14) X(18) X(20) X(28) X(40) X(48)
#else
#define OB_ICON_SIZES(X) X(10) X(12) X(14) X(16) X(24) X(32) X(40) X(48)
#endif

LV_FONT_DECLARE(ob_icons_10)
LV_FONT_DECLARE(ob_icons_12)
LV_FONT_DECLARE(ob_icons_14)
LV_FONT_DECLARE(ob_icons_16)
LV_FONT_DECLARE(ob_icons_18)
LV_FONT_DECLARE(ob_icons_20)
LV_FONT_DECLARE(ob_icons_24)
LV_FONT_DECLARE(ob_icons_28)
LV_FONT_DECLARE(ob_icons_32)
LV_FONT_DECLARE(ob_icons_40)
LV_FONT_DECLARE(ob_icons_48)
