#pragma once
#include <lvgl.h>

// ============================================================
// Theme – RUNTIME colour palette + font shortcuts for the marine UI.
//
// Colours are no longer compile-time literals: they live in the global
// `th` (UiTheme) struct, populated at boot from the active theme variant
// (dark/light) in the config (see Theme.cpp / applyThemeFromConfig()).
// The CLR_* macros below redirect to `th` so all existing call sites keep
// working unchanged. A theme change is applied by rebuilding the UI on the
// next boot (the PSRAM canvas arena cannot free, so live restyle isn't safe).
// ============================================================

// Every themeable colour as an lv_color_t, generated from the single field list.
#include "theme_colors.h"
struct UiTheme {
    #define X(n,d,l) lv_color_t n;
    THEME_COLOR_FIELDS(X)
    #undef X
};
extern UiTheme uiTheme;   // active theme (defined in Theme.cpp, filled at boot)

// Configurable sizes (shared light/dark). UI_* macros (UiConfig.h) redirect here.
#include "theme_sizes.h"
struct UiSizes {
    #define X(n,d) int16_t n;
    THEME_SIZE_FIELDS(X)
    #undef X
};
extern UiSizes uiSz;

void applyThemeFromConfig();   // copy active variant's colours + sizes into uiTheme/uiSz

// --- Colours (redirect to runtime theme) ------------------------------------
#define CLR_BG          (uiTheme.bg)
#define CLR_SURFACE     (uiTheme.surface)
#define CLR_BORDER      (uiTheme.border)
#define CLR_TEXT        (uiTheme.text)
#define CLR_TEXT_DIM    (uiTheme.textDim)
#define CLR_ACCENT      (uiTheme.accent)
// Foreground on coloured surfaces (button text on CLR_ACCENT, text over bars).
#define CLR_ON_ACCENT   (uiTheme.onAccent)
#define CLR_GREEN       (uiTheme.green)
#define CLR_YELLOW      (uiTheme.yellow)
#define CLR_RED         (uiTheme.red)
#define CLR_ORANGE      (uiTheme.orange)
#define CLR_PORT        (uiTheme.port)
#define CLR_STARBOARD   (uiTheme.starboard)
#define CLR_WIND        (uiTheme.wind)
#define CLR_GRID_LINE   (uiTheme.gridLine)
#define CLR_TRANSPARENT lv_color_hex(0x000000)   // used with opa=0 (not themeable)

// --- Opacity shortcuts -------------------------------------------------------
// LVGL 8 only defines opacity in 10% steps (LV_OPA_10 … LV_OPA_100).
// Define the missing fine-grained values here so the rest of the code compiles.
#ifndef LV_OPA_75
#  define LV_OPA_75  ((lv_opa_t)191)
#endif
#ifndef LV_OPA_35
#  define LV_OPA_35  ((lv_opa_t)89)
#endif
#ifndef LV_OPA_25
#  define LV_OPA_25  ((lv_opa_t)63)
#endif

#define OPA_FULL   LV_OPA_COVER
#define OPA_75     LV_OPA_75
#define OPA_50     LV_OPA_50
#define OPA_25     LV_OPA_25

// --- Fonts (runtime-configurable size per role) -----------------------------
// Each FONT_* role is a runtime pointer chosen from the compiled Montserrat
// sizes at boot (see Theme.cpp). FONT_* macros redirect so call sites are
// unchanged. The large numeric fonts (FONT_DEPTH/_XL) are runtime-configurable
// too via the "depth"/"gridHero" roles (mapped by bigFontBySize()).
#include "theme_fonts.h"
struct UiFonts {
    #define X(r,d) const lv_font_t *r;
    THEME_FONT_FIELDS(X)
    THEME_BIGFONT_FIELDS(X)
    #undef X
};
extern UiFonts uiFont;
const lv_font_t *montserratBySize(int sz);   // nearest enabled Montserrat font
const lv_font_t *bigFontBySize(int sz);      // 96/192 -> custom numeric; <=48 -> Montserrat

#define FONT_TINY    (uiFont.tiny)
#define FONT_SMALL   (uiFont.small)
#define FONT_MED     (uiFont.med)
#define FONT_LARGE   (uiFont.large)
#define FONT_XL      (uiFont.xl)
#define FONT_XXL     (uiFont.xxl)
#define FONT_HUGE    (uiFont.huge)

// Custom 96 px numeric font (digits, '.', '-', space, m/f/t) for the Depth
// readout, plus a 192 px variant for the large "hero" data-grid field. Both are
// generated by tools/gen_depth_font.py. FONT_DEPTH / FONT_DEPTH_XL now redirect
// to the configurable "depth"/"gridHero" roles: the size chosen in the WebUI
// maps via bigFontBySize() to depth_font_96 (96 px), depth_font_192 (192 px) or
// a Montserrat fallback (<=48 px).
LV_FONT_DECLARE(depth_font_96);
LV_FONT_DECLARE(depth_font_192);
#define FONT_DEPTH    (uiFont.depth)
#define FONT_DEPTH_XL (uiFont.gridHero)

// --- Dimensions -------------------------------------------------------------
#define NAV_BAR_H     0    // No bottom bar – navigation via side-overlay arrows + swipe
#if defined(BOARD_PANEL_1024X600)
// Stage 3: the content area renders NATIVELY at 600x600 in the 7B's middle
// column (LVGL transform-zoom was measured non-viable, see BoardConfig_7B.h).
// Screens designed on the 480 grid wrap their absolute pixel literals in
// UI_S(); everything derived from SCREEN_W/H adapts by itself.
//
// NAMING TRAP: on these boards SCREEN_W/H are NOT the screen. They are the
// 600x600 instrument CONTENT square inside the middle column, and they are
// orientation-independent by design - the square keeps its size whether the
// three blocks sit side by side or stacked, which is why none of the 17
// screens has to know about rotation. Code that really means "the whole
// logical screen" must call uiScreenW()/uiScreenH() below.
#define SCREEN_W    600
#define SCREEN_H    600
// 480-design pixels -> current grid: x1.25 with round-to-nearest, symmetric
// for negative offsets (-16 -> -20, mirroring 16 -> 20; C division truncates
// toward zero, so the bias constant must follow the sign). Exact for
// multiples of 4; for tiny odd values check the result once (3 -> 4).
#define UI_S(px)    (((px) * 5 + ((px) >= 0 ? 2 : -2)) / 4)
#define UI_SF 1.25f   // float scale for non-integer factors (float geometry, px-per-unit)
#else
#define SCREEN_W    480
#define SCREEN_H    480
#define UI_S(px)    (px)   // 4" and 480-simulator: the design grid IS the panel
#define UI_SF 1.0f    // float scale for non-integer factors (float geometry, px-per-unit)
#endif

// --- Runtime screen orientation ---------------------------------------------
// The rotation (config: display.rotation, 0/90/180/270) is a RUNTIME value, so
// layout code must ask these instead of using LCD_WIDTH/LCD_HEIGHT, which are
// the PHYSICAL panel dimensions and do not change when the picture is rotated.
//
// Note what does NOT change in portrait: the instrument square stays 600x600
// and the rail (88) and data sidebar (336) keep their exact sizes - 88 + 600 +
// 336 = 1024 works out the same whether the three sit side by side or stacked.
// That is why none of the 17 screens needs to know about orientation at all.
bool       uiPortrait();    // true when the logical screen is taller than wide
lv_coord_t uiScreenW();     // logical width  (what LVGL reports, post-rotation)
lv_coord_t uiScreenH();     // logical height

// --- Helper: apply dark style to a base object ------------------------------
static inline void styleCard(lv_obj_t *obj) {
    lv_obj_set_style_bg_color(obj, CLR_SURFACE, 0);
    lv_obj_set_style_bg_opa(obj, OPA_FULL, 0);
    lv_obj_set_style_border_color(obj, CLR_BORDER, 0);
    // From uiSz instead of fixed values: this makes the WebUI's card controls
    // (radius/padding/border) actually take effect — they previously did nothing.
    lv_obj_set_style_border_width(obj, uiSz.cardBorderW, 0);
    lv_obj_set_style_radius(obj, uiSz.cardRadius, 0);
    lv_obj_set_style_pad_all(obj, uiSz.cardPad, 0);
}

static inline void styleLabel(lv_obj_t *lbl, const lv_font_t *font, lv_color_t col = CLR_TEXT) {
    lv_obj_set_style_text_font(lbl, font, 0);
    lv_obj_set_style_text_color(lbl, col, 0);
}

// Clears LV_OBJ_FLAG_SCROLLABLE on every label in a subtree.
//
// WHY: LVGL makes every object scrollable - lv_obj_constructor sets the flag
// (lv_obj.c:441) and lv_label_constructor clears only CLICKABLE, never this.
// A scrollable object runs draw_scrollbar() in its DRAW_POST pass, once per
// draw-buffer strip, and lv_obj_get_scrollbar_area() then asks for scroll_top,
// scroll_bottom, scroll_left and scroll_right. Each of those calls
// lv_obj_get_self_height/width, which for a LABEL raises
// LV_EVENT_GET_SELF_SIZE, and lv_label.c:764 answers by measuring the entire
// text with lv_txt_get_size() - word-wrapping character by character through
// lv_font_get_glyph_width(), because lv_label.c:770 hard-codes
// LV_TEXT_FLAG_NONE. Four full text measurements, per label, per strip, for a
// scrollbar that can never appear because a label has no children to overflow.
//
// Measured on the 5B with a per-object DRAW_MAIN/DRAW_POST stopwatch: on the
// licence overlay, whose label holds 2 KB of text, that POST pass was 5.0 of
// every 5.0 seconds of wall clock. Clearing the flag took a scroll frame from
// 971 ms to 162 ms - 1.0 fps to 6.1 fps.
//
// No label in this UI scrolls itself: LV_LABEL_LONG_SCROLL animates the
// label's own text offset, not the object's scroll position, so the flag has
// no legitimate use here. Clearing it also stops a label from swallowing a
// drag meant for the container it sits in.
void uiDisableLabelScroll(lv_obj_t *root);

