#pragma once
#include <lvgl.h>

// ============================================================
// Theme – RUNTIME colour palette + font shortcuts for the marine UI.
//
// Colours are no longer compile-time literals: they live in the global
// `th` (UiTheme) struct, populated at boot from the active theme variant
// (dark/light) in the config (see Theme.cpp / applyThemeFromConfig()).
// The CLR_* macros below redirect to `th` so all existing call sites keep
// working unchanged. A theme change is applied by rebuilding the UI on the
// next boot (the PSRAM canvas arena cannot free, so live restyle isn't safe).
// ============================================================

// Every themeable colour as an lv_color_t, generated from the single field list.
#include "theme_colors.h"
struct UiTheme {
    #define X(n,d,l) lv_color_t n;
    THEME_COLOR_FIELDS(X)
    #undef X
};
extern UiTheme uiTheme;   // active theme (defined in Theme.cpp, filled at boot)

// Configurable sizes (shared light/dark). UI_* macros (UiConfig.h) redirect here.
#include "theme_sizes.h"
struct UiSizes {
    #define X(n,d) int16_t n;
    THEME_SIZE_FIELDS(X)
    #undef X
};
extern UiSizes uiSz;

void applyThemeFromConfig();   // copy active variant's colours + sizes into uiTheme/uiSz

// --- Colours (redirect to runtime theme) ------------------------------------
#define CLR_BG          (uiTheme.bg)
#define CLR_SURFACE     (uiTheme.surface)
#define CLR_BORDER      (uiTheme.border)
#define CLR_TEXT        (uiTheme.text)
#define CLR_TEXT_DIM    (uiTheme.textDim)
#define CLR_ACCENT      (uiTheme.accent)
// Foreground on coloured surfaces (button text on CLR_ACCENT, text over bars).
#define CLR_ON_ACCENT   (uiTheme.onAccent)
#define CLR_GREEN       (uiTheme.green)
#define CLR_YELLOW      (uiTheme.yellow)
#define CLR_RED         (uiTheme.red)
#define CLR_ORANGE      (uiTheme.orange)
#define CLR_PORT        (uiTheme.port)
#define CLR_STARBOARD   (uiTheme.starboard)
#define CLR_WIND        (uiTheme.wind)
#define CLR_GRID_LINE   (uiTheme.gridLine)
#define CLR_TRANSPARENT lv_color_hex(0x000000)   // used with opa=0 (not themeable)

// --- Opacity shortcuts -------------------------------------------------------
// LVGL 8 only defines opacity in 10% steps (LV_OPA_10 … LV_OPA_100).
// Define the missing fine-grained values here so the rest of the code compiles.
#ifndef LV_OPA_75
#  define LV_OPA_75  ((lv_opa_t)191)
#endif
#ifndef LV_OPA_35
#  define LV_OPA_35  ((lv_opa_t)89)
#endif
#ifndef LV_OPA_25
#  define LV_OPA_25  ((lv_opa_t)63)
#endif

#define OPA_FULL   LV_OPA_COVER
#define OPA_75     LV_OPA_75
#define OPA_50     LV_OPA_50
#define OPA_25     LV_OPA_25

// --- Fonts (runtime-configurable size per role) -----------------------------
// Each FONT_* role is a runtime pointer chosen from the compiled Montserrat
// sizes at boot (see Theme.cpp). FONT_* macros redirect so call sites are
// unchanged. The large numeric fonts (FONT_DEPTH/_XL) are runtime-configurable
// too via the "depth"/"gridHero" roles (mapped by bigFontBySize()).
#include "theme_fonts.h"
struct UiFonts {
    #define X(r,d) const lv_font_t *r;
    THEME_FONT_FIELDS(X)
    THEME_BIGFONT_FIELDS(X)
    #undef X
};
extern UiFonts uiFont;
const lv_font_t *montserratBySize(int sz);   // nearest enabled Montserrat font
const lv_font_t *bigFontBySize(int sz);      // 96/192 -> custom numeric; <=48 -> Montserrat

#define FONT_TINY    (uiFont.tiny)
#define FONT_SMALL   (uiFont.small)
#define FONT_MED     (uiFont.med)
#define FONT_LARGE   (uiFont.large)
#define FONT_XL      (uiFont.xl)
#define FONT_XXL     (uiFont.xxl)
#define FONT_HUGE    (uiFont.huge)

// Custom 96 px numeric font (digits, '.', '-', space, m/f/t) for the Depth
// readout, plus a 192 px variant for the large "hero" data-grid field. Both are
// generated by tools/gen_depth_font.py. FONT_DEPTH / FONT_DEPTH_XL now redirect
// to the configurable "depth"/"gridHero" roles: the size chosen in the WebUI
// maps via bigFontBySize() to depth_font_96 (96 px), depth_font_192 (192 px) or
// a Montserrat fallback (<=48 px).
LV_FONT_DECLARE(depth_font_96);
LV_FONT_DECLARE(depth_font_192);
#define FONT_DEPTH    (uiFont.depth)
#define FONT_DEPTH_XL (uiFont.gridHero)

// --- Dimensions -------------------------------------------------------------
#define NAV_BAR_H     0    // No bottom bar – navigation via side-overlay arrows + swipe
#define SCREEN_W    480
#define SCREEN_H    480

// --- Helper: apply dark style to a base object ------------------------------
static inline void styleCard(lv_obj_t *obj) {
    lv_obj_set_style_bg_color(obj, CLR_SURFACE, 0);
    lv_obj_set_style_bg_opa(obj, OPA_FULL, 0);
    lv_obj_set_style_border_color(obj, CLR_BORDER, 0);
    // From uiSz instead of fixed values: this makes the WebUI's card controls
    // (radius/padding/border) actually take effect — they previously did nothing.
    lv_obj_set_style_border_width(obj, uiSz.cardBorderW, 0);
    lv_obj_set_style_radius(obj, uiSz.cardRadius, 0);
    lv_obj_set_style_pad_all(obj, uiSz.cardPad, 0);
}

static inline void styleLabel(lv_obj_t *lbl, const lv_font_t *font, lv_color_t col = CLR_TEXT) {
    lv_obj_set_style_text_font(lbl, font, 0);
    lv_obj_set_style_text_color(lbl, col, 0);
}

