# gen_latin_supplement.py — generate the tiny "supplement" fonts that give the
# UI its umlauts.
#
# WHY THIS EXISTS
# LVGL's built-in Montserrat fonts cover ASCII 0x20-0x7E plus exactly two extra
# characters (degree U+00B0, bullet U+2022) plus ~60 FontAwesome icons. They have
# NO umlauts and no sharp-s, which is why the German UI used to be transliterated
# ("Oeldruck", "Schliessen") and why an en-dash rendered as an empty box.
#
# Rather than replacing the built-ins with fatter versions, we generate a very
# small font per size holding ONLY the missing characters and chain it via
# lv_font_t.fallback (supported since LVGL 8.3; the software renderer honours it
# through lv_font.c -> dsc_out->resolved_font -> lv_draw_sw_letter.c). The
# built-in fonts stay untouched and the cost is a few KB of flash.
#
# Usage:  python gen_latin_supplement.py
#         python gen_latin_supplement.py <ttf> <outdir>
import os
import sys
import freetype
from lvgl_font import emit_c

# Every size that is enabled in src/lv_conf.h as LV_FONT_MONTSERRAT_<n>.
# montserratBySize() can return any of these, so each needs a fallback partner.
SIZES = [10, 12, 14, 16, 18, 20, 22, 24, 28, 32, 36, 40, 44, 48]

# The characters the built-in fonts are missing and the UI actually wants.
CHARS = [
    "Ä", "Ö", "Ü",           # Ae Oe Ue
    "ä", "ö", "ü", "ß",  # ae oe ue sharp-s
    "±", "×",                      # plus-minus, multiplication sign
    "–",                                # en dash (rendered as a box before)
    "„", "“", "”",            # German and English typographic quotes
]

DEFAULT_TTF = "../download/fonts/montserrat/Montserrat-Medium.ttf"
DEFAULT_OUT = "../src/display/fonts"


def main():
    ttf    = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TTF
    outdir = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT

    # A character missing from the TTF would silently rasterise as .notdef — an
    # empty box, i.e. exactly the bug we are fixing. Fail loudly instead.
    face = freetype.Face(ttf)
    missing = [c for c in CHARS if face.get_char_index(c) == 0]
    if missing:
        raise SystemExit("ERROR: %s has no glyph for: %s"
                         % (os.path.basename(ttf),
                            " ".join("U+%04X" % ord(c) for c in missing)))

    os.makedirs(outdir, exist_ok=True)
    total = 0
    names = []
    for size in SIZES:
        symbol = "latin_suppl_%d" % size
        path   = os.path.join(outdir, symbol + ".c")
        src, stats = emit_c(ttf, size, CHARS, symbol, "gen_latin_supplement.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)
        total += stats["bitmap_bytes"]
        names.append((size, symbol))
        print("  %-20s %2d glyphs  %6d bitmap bytes" %
              (symbol + ".c", stats["glyphs"], stats["bitmap_bytes"]))

    # Companion header so Theme.cpp can pull them all in with one include.
    hdr = os.path.join(outdir, "latin_suppl.h")
    H = []
    H.append("// Generated by tools/gen_latin_supplement.py - DO NOT EDIT BY HAND.")
    H.append("//")
    H.append("// Fallback fonts supplying the glyphs LVGL's built-in Montserrat fonts lack")
    H.append("// (umlauts, sharp-s, en dash, typographic quotes, plus-minus, multiplication).")
    H.append("// Chained onto the built-ins via lv_font_t.fallback in Theme.cpp.")
    H.append("//")
    H.append("// Derived from the Montserrat typeface, Copyright 2011 The Montserrat")
    H.append("// Project Authors, SIL Open Font License 1.1 - see the individual .c files.")
    H.append("#pragma once")
    H.append("#include <lvgl.h>")
    H.append("")
    H.append("#ifdef __cplusplus")
    H.append('extern "C" {')
    H.append("#endif")
    H.append("")
    for size, symbol in names:
        H.append("extern const lv_font_t %s;" % symbol)
    H.append("")
    H.append("#ifdef __cplusplus")
    H.append("}")
    H.append("#endif")
    H.append("")
    with open(hdr, "w", encoding="utf-8") as f:
        f.write("\n".join(H))

    print("\nWrote %d fonts + latin_suppl.h to %s" % (len(SIZES), outdir))
    print("Total glyph bitmap data: %d bytes (%.1f KB)" % (total, total / 1024.0))


main()
