#!/usr/bin/env python3
"""Generate a 1-bpp equirectangular land/sea mask header for ClockScreen.

Source: Natural Earth 50m land (public domain) vector GeoJSON.
Renders land polygons (with lake/hole carve-outs) at SS x supersample, then
majority-downsamples to MW x MH and packs MSB-first, row-major, 1 bit/pixel
(1 = land). Output: src/display/screens/WorldMask.h
"""
import json, sys, os, urllib.request
from PIL import Image, ImageDraw
import numpy as np

MW, MH = 480, 200          # must match ClockScreen MW/MH
SS = 4                      # supersample factor
W, H = MW * SS, MH * SS

URLS = [
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson",
    "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/50m/physical/ne_50m_land.json",
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson",
]

def fetch():
    last = None
    for u in URLS:
        try:
            sys.stderr.write("fetch " + u + "\n")
            req = urllib.request.Request(u, headers={"User-Agent": "mask-gen"})
            with urllib.request.urlopen(req, timeout=40) as r:
                return json.loads(r.read().decode("utf-8"))
        except Exception as e:
            sys.stderr.write("  failed: %s\n" % e)
            last = e
    raise SystemExit("all sources failed: %s" % last)

def lonlat_to_xy(lon, lat):
    return ((lon + 180.0) / 360.0 * W, (90.0 - lat) / 180.0 * H)

def rings_of(geom):
    """Yield (exterior, [holes]) for each polygon part."""
    t = geom["type"]; c = geom["coordinates"]
    if t == "Polygon":
        yield c[0], c[1:]
    elif t == "MultiPolygon":
        for poly in c:
            yield poly[0], poly[1:]

def main():
    gj = fetch()
    img = Image.new("1", (W, H), 0)
    drw = ImageDraw.Draw(img)
    nland = nhole = 0
    for feat in gj["features"]:
        geom = feat.get("geometry")
        if not geom:
            continue
        for ext, holes in rings_of(geom):
            pts = [lonlat_to_xy(p[0], p[1]) for p in ext]
            if len(pts) >= 3:
                drw.polygon(pts, fill=1); nland += 1
            for h in holes:
                hp = [lonlat_to_xy(p[0], p[1]) for p in h]
                if len(hp) >= 3:
                    drw.polygon(hp, fill=0); nhole += 1
    sys.stderr.write("polys=%d holes=%d\n" % (nland, nhole))

    # Majority downsample SSxSS -> MWxMH.
    a = np.asarray(img, dtype=np.uint8).reshape(MH, SS, MW, SS)
    occ = a.sum(axis=(1, 3))                      # 0..SS*SS land subpixels
    land = (occ >= (SS * SS // 2)).astype(np.uint8)   # majority vote

    # Pack MSB-first, row-major.
    rowbytes = (MW + 7) // 8
    packed = bytearray(rowbytes * MH)
    for y in range(MH):
        for x in range(MW):
            if land[y, x]:
                packed[y * rowbytes + (x >> 3)] |= (0x80 >> (x & 7))

    out = os.path.join(os.path.dirname(__file__), "..", "src", "display", "screens", "WorldMask.h")
    out = os.path.abspath(out)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("// Auto-generated by tools/gen_world_mask.py — DO NOT EDIT.\n")
        f.write("// 1-bpp equirectangular land/sea mask (1 = land), MSB-first, row-major.\n")
        f.write("// Source: Natural Earth 50m land (public domain).\n")
        f.write("// lon -180..180 -> x 0..%d ; lat +90..-90 -> y 0..%d\n\n" % (MW, MH))
        f.write("#define WORLD_MASK_W %d\n#define WORLD_MASK_H %d\n" % (MW, MH))
        f.write("#define WORLD_MASK_ROWBYTES %d\n\n" % rowbytes)
        f.write("static const uint8_t WORLD_MASK[%d] = {\n" % len(packed))
        for i in range(0, len(packed), 20):
            chunk = packed[i:i + 20]
            f.write("  " + ",".join("0x%02x" % b for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write("static inline bool worldMaskLand(int x, int y) {\n")
        f.write("    if (x < 0 || x >= WORLD_MASK_W || y < 0 || y >= WORLD_MASK_H) return false;\n")
        f.write("    return (WORLD_MASK[y * WORLD_MASK_ROWBYTES + (x >> 3)] >> (7 - (x & 7))) & 1;\n")
        f.write("}\n")
    sys.stderr.write("wrote %s (%d bytes mask, land px=%d)\n" % (out, len(packed), int(land.sum())))

    # Also dump a PNG preview for eyeballing.
    prev = Image.fromarray((land * 255).astype(np.uint8), "L")
    prev.save(os.path.join(os.path.dirname(__file__), "world_mask_preview.png"))

if __name__ == "__main__":
    main()
