#!/usr/bin/env python3
"""
gen_icons.py - OpenBridge icon trial: builds NauticPinnace's icon fonts and web sprite.

    python tools/gen_icons.py [--export PATH] [--map PATH] [--check] [--preview PNG] [--verbose]

WHAT IT DOES
Reads the mapping file shared with NauticPi (tools/icons/openbridge-map.json, one entry
per icon) and the Figma export of the "OpenBridge Icon Pack" (CC BY 4.0), turns the icons
the firmware uses into single-colour shapes and writes:

  src/display/fonts/ob_icons_<px>.c   one 4-bpp LVGL bitmap font per pixel size
  src/display/fonts/ob_icons.h        code points (OB_ICON_*) and font declarations
  data/index.html                     the inline <svg> sprite between the BEGIN/END markers

WHERE THE EXPORT LIVES
Outside the repository: it also contains the OpenBridge logos and must never be
committed. Pass --export, set OPENBRIDGE_EXPORT, or keep it at
<parent of this repo>/Provenance/OpenBridge/openbridge-figma-export.json.

HOW AN ICON BECOMES SINGLE-COLOUR
Exactly as in NauticPi: the resolving and normalising code below is taken unchanged from
NauticPi's tools/gen_icons.py (same author), so both products draw the same shapes.

HOW IT BECOMES A FONT
The firmware cannot draw SVG (LVGL 8.4 has no vector decoder), so every icon is
rasterised here, at build time, into a glyph of a 4-bpp LVGL font in the Unicode Private
Use Area (from U+E000, in the order of PANEL_ICONS). The rasteriser is our own and small
on purpose:

- It fills each path with ITS OWN fill rule. Half of the icons use fill-rule="evenodd";
  a TrueType/FreeType route fills nonzero and closes their holes (anchor ring, depth
  marks, the "!" of the alarm). Filling per rule needs no outline surgery.
- Several paths of one icon are UNITED per sub-scanline before coverage is summed, so two
  shapes that share an edge leave no seam (alpha compositing would give 0.75 there).
- Coverage is exact horizontally and 16x supersampled vertically, then rounded to 4 bpp.
- Anything a font glyph cannot express - strokes, partial opacity, clip paths, masks,
  transforms - is an ERROR, not an approximation: the firmware set uses none of it today,
  and an icon added later that does must fail here rather than look subtly wrong.

THE GLYPH BOX
Each icon is drawn on its own grid (24 units, weather 32), scaled so that the WHOLE grid
is as tall as LVGL's Font Awesome gear (U+F013) in the Montserrat font of the same size,
vertically centred on that gear, and given the gear's advance width - the panel
equivalent of an SVG icon at 1em on a web page, which is how NauticPi shows them. An
earlier version scaled the grid's working area (20 of 24 units) to the gear instead: it
matched Font Awesome's visual weight, but the icons that use the full grid (sound-muted,
weather) then stood up to 4 px outside the advance and the line box, where LVGL clips
the label. Switching between the classic and the OpenBridge icons therefore moves
no label: widths and centre lines stay where they were. The Montserrat metrics are read
from the LVGL sources PlatformIO fetched (.pio/libdeps/*/lvgl), so build once first.

The output is deterministic: the same inputs give the same bytes. --check compares
instead of writing and exits 1 when anything on disk is stale.

Python 3 standard library only (PIL optional, for --preview). The script is MIT like the
rest of NauticPinnace; the artwork it produces is CC BY 4.0 - see the header of each
generated font and THIRD-PARTY-NOTICES.md.

OpenBridge icon trial: this script belongs to the trial (see ICONS-TRIAL.md).
"""
import argparse
import collections
import glob
import gzip
import json
import math
import os
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_MAP = os.path.join(HERE, 'icons', 'openbridge-map.json')
FONT_DIR = os.path.join(REPO, 'src', 'display', 'fonts')
HEADER_OUT = os.path.join(FONT_DIR, 'ob_icons.h')
INDEX_HTML = os.path.join(REPO, 'data', 'index.html')

SPRITE_ELEMENT_ID = 'ob-sprite'
SPRITE_BEGIN = '<!-- BEGIN OpenBridge icon trial: sprite, generated by tools/gen_icons.py - do not edit -->'
SPRITE_END = '<!-- END OpenBridge icon trial: sprite -->'

# ── what the firmware uses ───────────────────────────────────────────────────
# (macro name, map id). The ORDER fixes the code points: U+E000 + index. Append new
# icons at the end so existing code points stay put.
PANEL_ICONS = [
    ('WIND', 'wind'),
    ('STW', 'stw'),
    ('DEPTH', 'depth'),
    ('ENGINE', 'engine'),
    ('RUDDER', 'propulsion-rudder'),
    ('AIS', 'ais-target-activated-iec'),
    ('TREND', 'trend'),
    ('AUTOPILOT', 'command-autopilot'),
    ('SOUND', 'sound'),
    ('ROLL', 'roll'),
    ('ANCHORWATCH', 'anchorwatch'),
    ('TANK', 'tank'),
    ('BATTERY', 'battery-vertical-full'),
    ('WEATHER', 'weather'),
    ('TIME', 'time'),
    ('WAYPOINT_NEXT', 'waypoint-next-iec'),
    ('TABLE', 'table'),
    ('SETTINGS', 'settings-iec'),
    ('HOME', 'home'),
    ('CHEVRON_LEFT', 'chevron-left-google'),
    ('CHEVRON_RIGHT', 'chevron-right-google'),
    ('CLOSE', 'close-google'),
    ('ALARM', 'alarm'),
    ('SIMULATION', 'simulation'),
    ('MEDIA_PREV', 'media-skip-previous'),
    ('MEDIA_PLAY', 'media-play'),
    ('MEDIA_PAUSE', 'media-pause'),
    ('MEDIA_NEXT', 'media-skip-next'),
    ('SOUND_MUTED', 'sound-muted'),
]
PUA_BASE = 0xE000

# Pixel sizes = the font roles that carry an icon (tiny .. huge), per board, plus the
# smallest Montserrat the board compiles (10 resp. 12):
#   4-inch       10 12 14 16 24 32 40 48
#   1024x600     12 14 18 20 28 40 48   (every role scaled by UI_S, 48 is the cap)
# Theme.cpp chains the largest of these that is NOT larger than the Montserrat size it
# sits behind. LVGL draws a fallback glyph on the MAIN font's baseline and the label
# clips to the main font's line box, so a larger icon font would lose its top rows -
# and without the smallest size, a role set to 10 px would have had nothing smaller.
SIZES_SMALL = (10, 12, 14, 16, 24, 32, 40, 48)
SIZES_BIG = (12, 14, 18, 20, 28, 40, 48)

# What the web configuration shows. (ship-sailboat from the shared list is not used:
# the page has no own-ship marker, so it stays out of the sprite.)
WEB_ICONS = ['tide', 'sensor-gyro', 'save-proposal', 'file-download-google',
             'file-upload-google', 'clipboard', 'sync-google', 'wifi2-google', 'io',
             'palette-day', 'palette-dusk', 'palette-night', 'display-brilliance-iec',
             'delete', 'check-google', 'chevron-up-google', 'chevron-down-google',
             'chevron-right-google', 'image', 'simulation']

REFERENCE_CP = 0xF013          # LV_SYMBOL_SETTINGS: a full-height Font Awesome glyph
SUBSAMPLES = 16                # vertical sub-scanlines per pixel


# ══════════════════════════════════════════════════════════════════════════════
# TAKEN UNCHANGED from NauticPi tools/gen_icons.py (lines 57-543; same author, MIT).
# Resolving map entries against the export and normalising an icon to one colour
# must stay identical in both products, so this block is copied, not rewritten.
# Change it in NauticPi first, then copy it here again.
# ══════════════════════════════════════════════════════════════════════════════
SYMBOL_PREFIX = 'ob-'

SVG_NS = 'http://www.w3.org/2000/svg'
XLINK_NS = 'http://www.w3.org/1999/xlink'

SHAPES = {'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon'}
CONTAINERS = {'g'}
PAINT_SERVERS = {'linearGradient', 'radialGradient', 'pattern'}
DEFS_LIKE = {'defs', 'clipPath', 'mask', 'filter', 'stop'} | PAINT_SERVERS
DROPPED_ELEMENTS = {'title', 'desc', 'metadata'}

# Numeric attributes rounded to 2 decimals.
NUMERIC_ATTRS = {'x', 'y', 'width', 'height', 'rx', 'ry', 'cx', 'cy', 'r', 'x1', 'y1',
                 'x2', 'y2', 'fx', 'fy', 'points', 'stroke-width', 'stroke-miterlimit',
                 'stroke-dasharray', 'stroke-dashoffset', 'opacity', 'fill-opacity',
                 'stroke-opacity', 'stop-opacity', 'offset', 'viewBox'}
STROKE_ONLY_ATTRS = {'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'stroke-miterlimit',
                     'stroke-dasharray', 'stroke-dashoffset', 'stroke-opacity'}
FILL_ONLY_ATTRS = {'fill-rule', 'fill-opacity'}
# Output attribute order: geometry first, paint after, the rest in source order.
ATTR_ORDER = ['id', 'd', 'x', 'y', 'width', 'height', 'cx', 'cy', 'r', 'rx', 'ry',
              'x1', 'y1', 'x2', 'y2', 'points', 'transform', 'fill-rule', 'clip-rule',
              'fill', 'fill-opacity', 'stroke', 'stroke-width', 'stroke-opacity',
              'stroke-linecap', 'stroke-linejoin', 'stroke-miterlimit', 'stroke-dasharray',
              'stroke-dashoffset', 'opacity', 'clip-path', 'mask']

LIGHT_LUMA = 0.6         # above this a colour is "light"
LIGHT_OPACITY = 0.35     # light greys become currentColor at this opacity
GREY_CHROMA = 16         # max(r,g,b) - min(r,g,b) at or below this is a grey
MONO_STRATEGIES = {'holes', 'drop-light', 'flatten'}


class Report:
    def __init__(self):
        self.errors, self.warnings, self.notes = [], [], []

    def error(self, icon, msg):
        self.errors.append('%s: %s' % (icon, msg))

    def warn(self, icon, msg):
        self.warnings.append('%s: %s' % (icon, msg))

    def note(self, icon, msg):
        self.notes.append('%s: %s' % (icon, msg))


class IconError(Exception):
    pass


# ── numbers and path data ────────────────────────────────────────────────────

NUM_RE = re.compile(r'[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?')
NAN_RE = re.compile(r'nan|inf', re.IGNORECASE)
PATH_ARGS = {'M': 2, 'L': 2, 'H': 1, 'V': 1, 'C': 6, 'S': 4, 'Q': 4, 'T': 2, 'A': 7, 'Z': 0}


def fmt(value, decimals=2):
    """Shortest text for a number rounded to `decimals`: 0.50 -> .5, -0.00 -> 0."""
    s = '%.*f' % (decimals, value)
    if '.' in s:
        s = s.rstrip('0').rstrip('.')
    if s in ('-0', '', '-'):
        s = '0'
    if float(s) == 0:
        return '0'
    if s.startswith('0.'):
        s = s[1:]
    elif s.startswith('-0.'):
        s = '-' + s[2:]
    return s


def round_numbers(text, decimals=2):
    return NUM_RE.sub(lambda m: fmt(float(m.group()), decimals), text)


def parse_path(d):
    """Path data -> [(command, [[numbers], ...])]; implicit repeats become extra groups."""
    if NAN_RE.search(d):
        raise IconError("path data contains NaN/Inf (Figma export bug): %r" % d[:80])
    segs, i, n = [], 0, len(d)

    def skip(j):
        while j < n and (d[j].isspace() or d[j] == ','):
            j += 1
        return j

    while True:
        i = skip(i)
        if i >= n:
            break
        c = d[i]
        if not c.isalpha() or c.upper() not in PATH_ARGS:
            raise IconError('unexpected %r at %d in path data' % (c, i))
        i += 1
        k = PATH_ARGS[c.upper()]
        groups = []
        if k:
            while True:
                grp = []
                for j in range(k):
                    i = skip(i)
                    if c.upper() == 'A' and j in (3, 4):
                        if i < n and d[i] in '01':
                            grp.append(float(d[i]))
                            i += 1
                            continue
                        break
                    m = NUM_RE.match(d, i)
                    if not m:
                        break
                    grp.append(float(m.group()))
                    i = m.end()
                if len(grp) != k:
                    raise IconError('command %s needs %d numbers, found %d' % (c, k, len(grp)))
                groups.append(grp)
                j = skip(i)
                if j >= n or not (d[j].isdigit() or d[j] in '+-.'):
                    break
        segs.append((c, groups))
    if segs and segs[0][0] not in 'Mm':
        raise IconError('path data does not start with a moveto')
    return segs


def format_path(segs):
    out = []
    for cmd, groups in segs:
        out.append(cmd)
        last = None
        for grp in groups:
            for j, v in enumerate(grp):
                s = ('1' if v else '0') if (cmd in 'Aa' and j in (3, 4)) else fmt(v)
                if last is not None and not s.startswith('-'):
                    out.append(' ')
                out.append(s)
                last = s
    return ''.join(out)


def rect_to_segments(el):
    x, y = float(el.get('x', 0)), float(el.get('y', 0))
    w, h = float(el.get('width', 0)), float(el.get('height', 0))
    if el.get('rx') or el.get('ry'):
        raise IconError('rounded rect cannot be cut out as a hole')
    return [('M', [[x, y]]), ('H', [[x + w]]), ('V', [[y + h]]), ('H', [[x]]), ('Z', [])]


# ── colours ──────────────────────────────────────────────────────────────────

NAMED_COLOURS = {'white': (255, 255, 255), 'black': (0, 0, 0)}


def parse_colour(v):
    lv = v.strip().lower()
    if lv in NAMED_COLOURS:
        return NAMED_COLOURS[lv]
    m = re.fullmatch(r'#([0-9a-f])([0-9a-f])([0-9a-f])', lv)
    if m:
        return tuple(int(g * 2, 16) for g in m.groups())
    m = re.fullmatch(r'#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})(?:[0-9a-f]{2})?', lv)
    if m:
        return tuple(int(g, 16) for g in m.groups())
    m = re.fullmatch(r'rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,[^)]*)?\)', lv)
    if m:
        return tuple(int(g) for g in m.groups())
    return None


def paint_kind(v):
    """none | current | url | white | light-grey | light | dark | unknown"""
    if v is None:
        return 'none'
    lv = v.strip().lower()
    if lv in ('none', 'transparent', ''):
        return 'none'
    if lv == 'currentcolor':
        return 'current'
    if lv.startswith('url('):
        return 'url'
    rgb = parse_colour(v)
    if rgb is None:
        return 'unknown'
    if rgb == (255, 255, 255):
        return 'white'
    luma = (0.299 * rgb[0] + 0.587 * rgb[1] + 0.114 * rgb[2]) / 255.0
    if luma > LIGHT_LUMA:
        return 'light-grey' if max(rgb) - min(rgb) <= GREY_CHROMA else 'light'
    return 'dark'


# ── resolving map entries against the export ─────────────────────────────────

def sanitise(name):
    s = unicodedata.normalize('NFC', name)
    for a, b in (('å', 'aa'), ('æ', 'ae'), ('ø', 'oe'), ('Å', 'aa'), ('Æ', 'ae'), ('Ø', 'oe')):
        s = s.replace(a, b)
    return re.sub(r'\s+', '', s).replace('%', '').lower()


def nearest_frame(item):
    frames = [p.strip() for p in (item.get('path') or [])
              if p.strip().lower() not in ('outlined', 'filled')]
    return frames[-1] if frames else None


class ExportIndex:
    def __init__(self, items):
        self.by_node = {}
        self.by_name = collections.defaultdict(list)
        self.by_sanitised = collections.defaultdict(list)
        self.by_frame = collections.defaultdict(list)
        for it in items:
            self.by_node[it['id']] = it
            self.by_name[it['name']].append(it)
            self.by_sanitised[sanitise(it['name'])].append(it)
            frame = nearest_frame(it)
            if frame:
                self.by_frame[frame].append(it)

    def resolve(self, entry):
        """-> (item, how). Raises IconError when nothing or more than one component fits."""
        rid, figma, node = entry['id'], entry.get('figma'), entry.get('node')
        if node:
            it = self.by_node.get(node)
            if it is None:
                raise IconError('node %s is not in the export' % node)
            return it, 'node'
        steps = (('name', self.by_name, figma or rid),
                 ('name', self.by_name, rid),
                 ('sanitised', self.by_sanitised, sanitise(figma or rid)),
                 ('sanitised', self.by_sanitised, sanitise(rid)),
                 ('frame', self.by_frame, rid))
        for how, table, key in steps:
            cands = table.get(key) or []
            if len(cands) == 1:
                return cands[0], how
            if len(cands) > 1:
                raise IconError('%s %r is ambiguous (%s); give "node" in the map'
                                % (how, key, ', '.join(c['id'] for c in cands)))
        raise IconError('no Figma component found')


# ── converting one icon ──────────────────────────────────────────────────────

def local(tag):
    return tag.split('}', 1)[1] if tag.startswith('{') else tag


def attr_name(name):
    if name.startswith('{%s}' % XLINK_NS):
        return 'href'
    return local(name)


def normalise_attrs(el):
    """Plain attribute dict (xlink:href -> href; style="a:b" -> attributes)."""
    attrs = collections.OrderedDict()
    for k, v in el.attrib.items():
        attrs[attr_name(k)] = v
    style = attrs.pop('style', None)
    if style:
        for part in style.split(';'):
            if ':' in part:
                k, v = part.split(':', 1)
                attrs.setdefault(k.strip(), v.strip())
    return attrs


class Node:
    def __init__(self, tag, attrs, children=None):
        self.tag, self.attrs, self.children = tag, attrs, children or []


def convert_icon(icon_id, item, mono, rep):
    try:
        root = ET.fromstring(item['svg'])
    except ET.ParseError as ex:
        raise IconError('SVG does not parse: %s' % ex)
    if local(root.tag) != 'svg':
        raise IconError('root element is <%s>, not <svg>' % local(root.tag))
    rattrs = normalise_attrs(root)
    view_box = rattrs.get('viewBox') or '0 0 %s %s' % (fmt(item['w']), fmt(item['h']))
    if NAN_RE.search(view_box):
        raise IconError('viewBox contains NaN')
    view_box = round_numbers(view_box)

    ids = {}
    for el in root.iter():
        if 'id' in el.attrib:
            ids[el.attrib['id']] = '%s%s-%s' % (SYMBOL_PREFIX, icon_id, el.attrib['id'])

    def fix_refs(v):
        v = re.sub(r'url\(\s*#([^)\s]+)\s*\)',
                   lambda m: 'url(#%s)' % ids.get(m.group(1), m.group(1)), v)
        if v.startswith('#') and v[1:] in ids:
            v = '#' + ids[v[1:]]
        return v

    def round_attrs(attrs):
        for k in list(attrs):
            v = attrs[k]
            if NAN_RE.search(v) and k in NUMERIC_ATTRS | {'d', 'transform'}:
                raise IconError('attribute %s contains NaN: %r' % (k, v[:60]))
            if k == 'd':
                attrs[k] = format_path(parse_path(v))
            elif k == 'transform':
                attrs[k] = round_numbers(v, 4)
            elif k in NUMERIC_ATTRS:
                attrs[k] = round_numbers(v)
            elif k == 'id':
                attrs[k] = ids[v]
            else:
                attrs[k] = fix_refs(v)

    paint_notes = collections.Counter()

    def recolour(value, channel, attrs):
        """-> (new paint, opacity factor) or (None, None) to drop the channel."""
        kind = paint_kind(value)
        if kind == 'none':
            return 'none', 1.0
        if kind == 'current':
            return 'currentColor', 1.0
        if mono == 'flatten':
            return 'currentColor', 1.0
        if kind == 'url':
            rep.warn(icon_id, '%s=%s (a paint server) flattened to currentColor' % (channel, value))
            return 'currentColor', 1.0
        if kind == 'unknown':
            rep.warn(icon_id, '%s=%s is no known colour; treated as currentColor' % (channel, value))
            return 'currentColor', 1.0
        if kind in ('white', 'light', 'light-grey') and mono == 'drop-light':
            paint_notes['dropped light layer %s' % value] += 1
            return None, None
        if kind == 'white':
            return None, None      # the caller decides: hole or report
        if kind == 'light-grey':
            paint_notes['light grey %s -> currentColor at %s' % (value, fmt(LIGHT_OPACITY))] += 1
            return 'currentColor', LIGHT_OPACITY
        if kind == 'light':
            rep.warn(icon_id, 'light colour %s=%s flattened to currentColor (consider "mono")'
                     % (channel, value))
            return 'currentColor', 1.0
        return 'currentColor', 1.0

    def walk(el, inh_fill, inh_stroke, context):
        tag = local(el.tag)
        if tag in DROPPED_ELEMENTS:
            return None
        if tag == 'text' or tag == 'image' or tag == 'foreignObject':
            raise IconError('<%s> is not supported in an icon' % tag)
        if (el.text or '').strip() and tag not in ('style',):
            rep.warn(icon_id, 'text content in <%s> ignored' % tag)
        attrs = normalise_attrs(el)
        ctx = context
        if tag == 'clipPath':
            ctx = 'clip'
        elif tag == 'mask':
            ctx = 'mask'
        elif tag in PAINT_SERVERS or tag in ('filter', 'defs'):
            ctx = ctx if ctx in ('clip', 'mask') else 'defs'

        fill = attrs.get('fill', inh_fill)
        stroke = attrs.get('stroke', inh_stroke)
        round_attrs(attrs)

        if tag in SHAPES and ctx == 'draw':
            node = shape(tag, attrs, fill, stroke)
            return node
        if tag in SHAPES and ctx == 'clip':
            # Geometry only: paint inside a clipPath means nothing.
            for k in ('fill', 'stroke', 'fill-opacity', 'stroke-opacity', 'opacity'):
                attrs.pop(k, None)
            return Node(tag, attrs)
        if tag in SHAPES:
            return Node(tag, attrs)          # mask/defs content: colours kept (luminance)

        if tag in CONTAINERS and ctx == 'draw':
            attrs.pop('fill', None)
            attrs.pop('stroke', None)
        elif tag not in CONTAINERS and tag not in DEFS_LIKE and tag != 'use':
            rep.warn(icon_id, 'unexpected element <%s> kept as it is' % tag)
        kids = []
        for ch in el:
            n = walk(ch, fill, stroke, ctx)
            if n is not None:
                kids.append(n)
        return Node(tag, attrs, kids)

    def shape(tag, attrs, fill, stroke):
        attrs.pop('clip-rule', None)                     # only means something in a clipPath
        new_fill, fill_op = recolour(fill, 'fill', attrs)
        new_stroke, stroke_op = recolour(stroke, 'stroke', attrs)
        fill_white = paint_kind(fill) == 'white' and mono not in ('flatten', 'drop-light')
        stroke_white = paint_kind(stroke) == 'white' and mono not in ('flatten', 'drop-light')
        node = Node(tag, attrs)
        if fill_white:
            if mono == 'holes' and paint_kind(stroke) == 'none':
                node.hole = True
                return node
            rep.warn(icon_id, 'white fill on <%s> outside a clipPath dropped' % tag)
        if stroke_white:
            rep.warn(icon_id, 'white stroke on <%s> outside a clipPath dropped' % tag)
        if mono == 'holes' and paint_kind(fill) == 'none' and paint_kind(stroke) != 'none':
            paint_notes['stroke-only outline dropped'] += 1
            return None
        new_fill = new_fill or 'none'
        new_stroke = new_stroke or 'none'
        if new_fill == 'none' and new_stroke == 'none':
            paint_notes['unpainted <%s> dropped' % tag] += 1
            return None
        attrs['fill'] = new_fill
        attrs['stroke'] = new_stroke
        if new_fill == 'none':
            for k in FILL_ONLY_ATTRS:
                attrs.pop(k, None)
        elif fill_op is not None and fill_op < 1:
            attrs['fill-opacity'] = fmt(float(attrs.get('fill-opacity', 1)) * fill_op)
        if new_stroke == 'none':
            for k in STROKE_ONLY_ATTRS:
                attrs.pop(k, None)
        elif stroke_op is not None and stroke_op < 1:
            attrs['stroke-opacity'] = fmt(float(attrs.get('stroke-opacity', 1)) * stroke_op)
        return node

    kids = []
    for ch in root:
        n = walk(ch, rattrs.get('fill', 'black'), rattrs.get('stroke', 'none'), 'draw')
        if n is not None:
            kids.append(n)

    # "holes": cut white shapes out of the nearest filled path painted before them.
    def cut_holes(nodes):
        out, host = [], None
        for n in nodes:
            if getattr(n, 'hole', False):
                if host is None:
                    raise IconError('white shape without a filled shape below it')
                segs = parse_path(n.attrs['d']) if n.tag == 'path' else \
                    rect_to_segments(n.attrs) if n.tag == 'rect' else None
                if segs is None:
                    raise IconError('cannot cut a <%s> out as a hole' % n.tag)
                if segs[0][0] == 'm':
                    segs[0] = ('M', segs[0][1])     # a leading m is absolute by definition
                host.attrs['d'] = host.attrs['d'] + format_path(segs)
                host.attrs['fill-rule'] = 'evenodd'
                paint_notes['white shape cut out as a hole (evenodd)'] += 1
                continue
            n.children = cut_holes(n.children)
            if n.tag == 'path' and n.attrs.get('fill', 'none') != 'none':
                host = n
            elif n.tag == 'rect' and n.attrs.get('fill', 'none') != 'none' and mono == 'holes':
                n.tag, n.attrs['d'] = 'path', format_path(rect_to_segments(n.attrs))
                for k in ('x', 'y', 'width', 'height'):
                    n.attrs.pop(k, None)
                host = n
            out.append(n)
        return out

    kids = cut_holes(kids)
    if mono == 'holes' and not paint_notes['white shape cut out as a hole (evenodd)']:
        rep.warn(icon_id, 'mono "holes" found no white shape to cut out')
    for msg, cnt in sorted(paint_notes.items()):
        rep.note(icon_id, msg + (' (x%d)' % cnt if cnt > 1 else ''))
    if not kids:
        raise IconError('nothing left to draw')
    return view_box, kids


# ── serialising ──────────────────────────────────────────────────────────────

def esc(v):
    return v.replace('&', '&amp;').replace('<', '&lt;').replace('"', '&quot;')


def ordered(attrs):
    keys = [k for k in ATTR_ORDER if k in attrs] + [k for k in attrs if k not in ATTR_ORDER]
    return ''.join(' %s="%s"' % (k, esc(attrs[k])) for k in keys)


def serialise(node):
    if not node.children:
        return '<%s%s/>' % (node.tag, ordered(node.attrs))
    return '<%s%s>%s</%s>' % (node.tag, ordered(node.attrs),
                              ''.join(serialise(c) for c in node.children), node.tag)
# ══════════════════════════════════════════════════════════════════════════════
# END of the block taken from NauticPi.
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# Everything below is NauticPinnace's own: rasterising, the LVGL font, the sprite.
# ══════════════════════════════════════════════════════════════════════════════

# ── the export ───────────────────────────────────────────────────────────────

def find_export(arg):
    """--export, then $OPENBRIDGE_EXPORT, then Provenance/OpenBridge/ next to the repo or
    next to any sibling folder of it (where the NauticPi workspace keeps it) - the
    latter only if it is unambiguous."""
    tried = []
    name = os.path.join('Provenance', 'OpenBridge', 'openbridge-figma-export.json')
    parent = os.path.dirname(REPO)
    for cand in (arg, os.environ.get('OPENBRIDGE_EXPORT'), os.path.join(parent, name)):
        if cand:
            tried.append(cand)
            if os.path.isfile(cand):
                return cand, tried
    hits = sorted(glob.glob(os.path.join(parent, '*', name)))
    tried.append(os.path.join(parent, '*', name) + ' (%d found)' % len(hits))
    if len(hits) == 1:
        return hits[0], tried
    return None, tried


def load_icons(export_path, map_path, ids, rep):
    """-> {id: (view_box, kids)} for the requested map ids, normalised like NauticPi."""
    with open(map_path, encoding='utf-8') as f:
        mp = json.load(f)
    with open(export_path, encoding='utf-8') as f:
        ex = json.load(f)
    idx = ExportIndex(ex['items'])
    by_id = {e['id']: e for e in mp['icons']}
    out = {}
    for rid in ids:
        if rid in out:
            continue
        entry = by_id.get(rid)
        if entry is None:
            rep.error(rid, 'not in the map (add one line to BOTH repositories)')
            continue
        try:
            item, _how = idx.resolve(entry)
            out[rid] = convert_icon(rid, item, entry.get('mono'), rep)
        except IconError as ex_:
            rep.error(rid, str(ex_))
    return mp, out


# ── geometry: path data -> closed polygons ───────────────────────────────────

def _cubic(p0, p1, p2, p3, out):
    ctrl = (math.dist(p0, p1) + math.dist(p1, p2) + math.dist(p2, p3))
    n = max(4, min(96, int(math.ceil(ctrl * 4))))
    for i in range(1, n + 1):
        t = i / n
        a, b, c, d = (1 - t) ** 3, 3 * t * (1 - t) ** 2, 3 * t * t * (1 - t), t ** 3
        out.append((a * p0[0] + b * p1[0] + c * p2[0] + d * p3[0],
                    a * p0[1] + b * p1[1] + c * p2[1] + d * p3[1]))


def _quad(p0, p1, p2, out):
    ctrl = math.dist(p0, p1) + math.dist(p1, p2)
    n = max(4, min(96, int(math.ceil(ctrl * 4))))
    for i in range(1, n + 1):
        t = i / n
        a, b, c = (1 - t) ** 2, 2 * t * (1 - t), t * t
        out.append((a * p0[0] + b * p1[0] + c * p2[0], a * p0[1] + b * p1[1] + c * p2[1]))


def _arc(p1, rx, ry, phi_deg, fa, fs, p2, out):
    """SVG elliptical arc (implementation notes F.6.5) appended as line points."""
    x1, y1 = p1
    x2, y2 = p2
    if (x1, y1) == (x2, y2):
        return
    rx, ry = abs(rx), abs(ry)
    if rx == 0 or ry == 0:
        out.append((x2, y2))
        return
    phi = math.radians(phi_deg % 360)
    cp, sp = math.cos(phi), math.sin(phi)
    dx2, dy2 = (x1 - x2) / 2, (y1 - y2) / 2
    x1p = cp * dx2 + sp * dy2
    y1p = -sp * dx2 + cp * dy2
    lam = (x1p * x1p) / (rx * rx) + (y1p * y1p) / (ry * ry)
    if lam > 1:
        s = math.sqrt(lam)
        rx, ry = rx * s, ry * s
    num = rx * rx * ry * ry - rx * rx * y1p * y1p - ry * ry * x1p * x1p
    den = rx * rx * y1p * y1p + ry * ry * x1p * x1p
    coef = math.sqrt(max(0.0, num / den)) if den else 0.0
    if fa == fs:
        coef = -coef
    cxp = coef * rx * y1p / ry
    cyp = -coef * ry * x1p / rx
    cx = cp * cxp - sp * cyp + (x1 + x2) / 2
    cy = sp * cxp + cp * cyp + (y1 + y2) / 2

    def ang(ux, uy, vx, vy):
        return math.atan2(ux * vy - uy * vx, ux * vx + uy * vy)

    ux, uy = (x1p - cxp) / rx, (y1p - cyp) / ry
    vx, vy = (-x1p - cxp) / rx, (-y1p - cyp) / ry
    th1 = ang(1, 0, ux, uy)
    dth = ang(ux, uy, vx, vy)
    if not fs and dth > 0:
        dth -= 2 * math.pi
    elif fs and dth < 0:
        dth += 2 * math.pi
    n = max(4, min(128, int(math.ceil(abs(dth) * max(rx, ry) * 4))))
    for i in range(1, n + 1):
        a = th1 + dth * i / n
        ca, sa = math.cos(a), math.sin(a)
        out.append((cx + rx * ca * cp - ry * sa * sp, cy + rx * ca * sp + ry * sa * cp))
    out[-1] = (x2, y2)                        # land exactly on the end point


def path_polygons(d):
    """Path data -> list of closed polygons (point lists) in user units."""
    polys, cur = [], None
    x = y = sx = sy = 0.0
    last_cmd, last_ctrl = '', None
    for cmd, groups in parse_path(d):
        C, rel = cmd.upper(), cmd.islower()
        if C == 'Z':
            if cur:
                polys.append(cur)
            cur = None
            x, y = sx, sy
            last_cmd, last_ctrl = 'Z', None
            continue
        for gi, g in enumerate(groups):
            ox, oy = (x, y) if rel else (0.0, 0.0)
            if C == 'M' and gi == 0:
                if cur:
                    polys.append(cur)           # an unclosed subpath is filled closed
                x, y = ox + g[0], oy + g[1]
                cur, sx, sy = [(x, y)], x, y
                last_cmd, last_ctrl = 'M', None
                continue
            if cur is None:                     # drawing right after Z: start at (x, y)
                cur, sx, sy = [(x, y)], x, y
            if C in ('M', 'L'):                 # extra M pairs are implicit linetos
                x, y = ox + g[0], oy + g[1]
                cur.append((x, y))
                last_ctrl = None
            elif C == 'H':
                x = ox + g[0]
                cur.append((x, y))
                last_ctrl = None
            elif C == 'V':
                y = oy + g[0]
                cur.append((x, y))
                last_ctrl = None
            elif C == 'C':
                c1 = (ox + g[0], oy + g[1])
                c2 = (ox + g[2], oy + g[3])
                p = (ox + g[4], oy + g[5])
                _cubic((x, y), c1, c2, p, cur)
                (x, y), last_ctrl = p, c2
            elif C == 'S':
                c1 = (2 * x - last_ctrl[0], 2 * y - last_ctrl[1]) \
                    if last_cmd in ('C', 'S') and last_ctrl else (x, y)
                c2 = (ox + g[0], oy + g[1])
                p = (ox + g[2], oy + g[3])
                _cubic((x, y), c1, c2, p, cur)
                (x, y), last_ctrl = p, c2
            elif C == 'Q':
                c = (ox + g[0], oy + g[1])
                p = (ox + g[2], oy + g[3])
                _quad((x, y), c, p, cur)
                (x, y), last_ctrl = p, c
            elif C == 'T':
                c = (2 * x - last_ctrl[0], 2 * y - last_ctrl[1]) \
                    if last_cmd in ('Q', 'T') and last_ctrl else (x, y)
                p = (ox + g[0], oy + g[1])
                _quad((x, y), c, p, cur)
                (x, y), last_ctrl = p, c
            elif C == 'A':
                p = (ox + g[5], oy + g[6])
                _arc((x, y), g[0], g[1], g[2], int(g[3]), int(g[4]), p, cur)
                (x, y), last_ctrl = p, None
            last_cmd = C
    if cur:
        polys.append(cur)
    return [p for p in polys if len(p) >= 3]


# ── rasterising ──────────────────────────────────────────────────────────────

FONT_UNSUPPORTED_ATTRS = ('transform', 'clip-path', 'mask', 'opacity', 'fill-opacity',
                          'stroke-opacity')


def icon_shapes(rid, kids):
    """Normalised node tree -> [(polygons, rule)]. Refuses what a glyph cannot hold."""
    shapes = []

    def walk(n):
        for k in FONT_UNSUPPORTED_ATTRS:
            if k in n.attrs:
                raise IconError('%s on <%s> cannot be expressed in a font glyph' % (k, n.tag))
        if n.tag == 'g':
            for c in n.children:
                walk(c)
            return
        if n.tag in ('defs', 'clipPath', 'mask'):
            raise IconError('<%s> cannot be expressed in a font glyph' % n.tag)
        if n.tag != 'path':
            raise IconError('<%s> is not supported by the font rasteriser yet' % n.tag)
        if n.attrs.get('stroke', 'none') != 'none':
            raise IconError('a stroked path cannot be expressed in a font glyph yet')
        if n.attrs.get('fill', 'none') == 'none':
            return
        rule = n.attrs.get('fill-rule', 'nonzero')
        if rule not in ('nonzero', 'evenodd'):
            raise IconError('unknown fill-rule %r' % rule)
        shapes.append((path_polygons(n.attrs['d']), rule))

    for k in kids:
        walk(k)
    if not shapes:
        raise IconError('no filled path')
    return shapes


def rasterise(shapes, view_box, scale, left, top, w, h, pad=0):
    """Coverage grid ((h + 2 pad) rows x (w + 2 pad) cols, 0..1) of the united shapes.

    User point (ux, uy) lands on pixel coordinate ((ux - vx) * scale - left,
    (uy - vy) * scale - top); pixel (c, r) covers [c, c+1) x [r, r+1), for c and r
    from -pad to w + pad - 1, stored at [r + pad][c + pad].

    The pad widens the grid by INTEGER indices only. Shifting the coordinates instead
    (left - pad) would move every point by an ulp, and coverage values that sit exactly
    on a 4-bit step would flip - measured: a 3 px wider canvas changed bitmaps at 24 and
    48 px and, through Python's round-half-to-even, offsets at 12 and 14 px."""
    vx, vy = view_box[0], view_box[1]
    paths = []
    for polys, rule in shapes:
        edges = []
        for poly in polys:
            pts = [((px - vx) * scale - left, (py - vy) * scale - top) for px, py in poly]
            for i in range(len(pts)):
                x0, y0 = pts[i]
                x1, y1 = pts[(i + 1) % len(pts)]
                if y0 != y1:
                    edges.append((x0, y0, x1, y1))
        # Bucket edges by pixel row so each sub-scanline only tests a handful.
        rows = [[] for _ in range(h + 2 * pad)]
        for e in edges:
            lo, hi = min(e[1], e[3]), max(e[1], e[3])
            for r in range(max(-pad, int(math.floor(lo))), min(h + pad, int(math.ceil(hi)))):
                rows[r + pad].append(e)
        paths.append((rows, rule))

    W = w + 2 * pad
    cov = [[0.0] * W for _ in range(h + 2 * pad)]
    wgt = 1.0 / SUBSAMPLES
    for r in range(-pad, h + pad):
        row = cov[r + pad]
        for s in range(SUBSAMPLES):
            y = r + (s + 0.5) / SUBSAMPLES
            spans = []
            for rows, rule in paths:
                xs = []
                for x0, y0, x1, y1 in rows[r + pad]:
                    if y0 <= y < y1:
                        xs.append((x0 + (y - y0) * (x1 - x0) / (y1 - y0), 1))
                    elif y1 <= y < y0:
                        xs.append((x0 + (y - y0) * (x1 - x0) / (y1 - y0), -1))
                if not xs:
                    continue
                xs.sort()
                if rule == 'evenodd':
                    for i in range(0, len(xs) - 1, 2):
                        spans.append((xs[i][0], xs[i + 1][0]))
                else:
                    wind, start = 0, None
                    for xv, dv in xs:
                        before = wind
                        wind += dv
                        if before == 0 and wind != 0:
                            start = xv
                        elif before != 0 and wind == 0:
                            spans.append((start, xv))
            if not spans:
                continue
            spans.sort()
            merged = [list(spans[0])]
            for a, b in spans[1:]:
                if a <= merged[-1][1]:
                    if b > merged[-1][1]:
                        merged[-1][1] = b
                else:
                    merged.append([a, b])
            for a, b in merged:
                a, b = max(float(-pad), a), min(float(w + pad), b)
                if b <= a:
                    continue
                ia, ib = int(math.floor(a)), int(math.floor(b))
                if ia == ib:
                    row[ia + pad] += (b - a) * wgt
                    continue
                row[ia + pad] += (ia + 1 - a) * wgt
                for c in range(ia + 1, ib):
                    row[c + pad] += wgt
                if ib < w + pad:
                    row[ib + pad] += (b - ib) * wgt
    return cov


# ── LVGL font metrics of the Montserrat reference ────────────────────────────

def find_montserrat(size):
    pats = glob.glob(os.path.join(REPO, '.pio', 'libdeps', '*', 'lvgl', 'src', 'font',
                                  'lv_font_montserrat_%d.c' % size))
    if not pats:
        raise SystemExit('ERROR: lv_font_montserrat_%d.c not found under .pio/libdeps - build '
                         'the project once so PlatformIO fetches LVGL.' % size)
    return sorted(pats)[0]


def montserrat_reference(size, cp=REFERENCE_CP):
    """-> dict(line_height, base_line, adv_w, box_w, box_h, ofs_x, ofs_y) for code point cp."""
    with open(find_montserrat(size), encoding='utf-8', errors='replace') as f:
        src = f.read()
    m = re.search(r'glyph_dsc\[\]\s*=\s*\{(.*?)\n\};', src, re.S)
    dscs = re.findall(r'\{\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), '
                      r'\.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)\}', m.group(1))
    lists = {}
    for name, body in re.findall(r'static const uint16_t (unicode_list_\d+)\[\] = \{(.*?)\};',
                                 src, re.S):
        lists[name] = [int(v, 0) for v in re.findall(r'0x[0-9a-fA-F]+|\d+', body)]
    gid = None
    for rs, rl, gs, ul in re.findall(
            r'\.range_start = (\d+), \.range_length = (\d+), \.glyph_id_start = (\d+),\s*'
            r'\.unicode_list = (\w+)', src):
        rs, rl, gs = int(rs), int(rl), int(gs)
        if not rs <= cp < rs + rl:
            continue
        if ul == 'NULL':
            gid = gs + (cp - rs)
        elif (cp - rs) in lists[ul]:
            gid = gs + lists[ul].index(cp - rs)
    if gid is None:
        raise SystemExit('ERROR: U+%04X not found in %s' % (cp, find_montserrat(size)))
    # dscs includes the reserved id-0 row (it matches the pattern too), so the glyph id
    # IS the index. An earlier dscs[gid - 1] read U+F011 (power) instead of the gear -
    # the same box at most sizes, one pixel off at 18.
    _bi, adv, bw, bh, ox, oy = (int(v) for v in dscs[gid])
    lh = int(re.search(r'\.line_height = (\d+)', src).group(1))
    bl = int(re.search(r'\.base_line = (\d+)', src).group(1))
    return dict(line_height=lh, base_line=bl, adv_w=adv, box_w=bw, box_h=bh, ofs_x=ox, ofs_y=oy)


def make_glyph(rid, view_box, shapes, size, ref):
    """-> (adv_w16, box_w, box_h, ofs_x, ofs_y, rows of 0..15 values)."""
    grid = max(view_box[2], view_box[3])
    side = float(ref['box_h'])                           # pixels the longer grid side spans
    scale = side / grid
    adv_px = ref['adv_w'] / 16.0
    centre_y = ref['ofs_y'] + ref['box_h'] / 2.0         # above the baseline
    core = int(math.ceil(side)) + 2                      # the grid plus 1 px per edge
    canvas_left = int(round(adv_px / 2.0 - core / 2.0))
    canvas_bottom = int(round(centre_y - core / 2.0))
    # A non-square grid is centred on its shorter axis, as the web sprite shows it
    # (preserveAspectRatio xMidYMid).
    off_x = (core - view_box[2] * scale) / 2.0
    off_y = (core - view_box[3] * scale) / 2.0
    # MARGIN more pixels all round, so geometry drawn a little outside its view box is
    # still rasterised - fit_into_cell() then decides, and reports, what stays.
    MARGIN = 3
    cov = rasterise(shapes, view_box, scale, -off_x, -off_y, core, core, pad=MARGIN)
    n = core + 2 * MARGIN
    canvas_left -= MARGIN
    canvas_bottom -= MARGIN
    vals = [[min(15, max(0, int(v * 15 + 0.5))) for v in row] for row in cov]
    nz_rows = [r for r in range(n) if any(vals[r])]
    nz_cols = [c for c in range(n) if any(vals[r][c] for r in range(n))]
    if not nz_rows:
        raise IconError('renders empty at %d px' % size)
    r0, r1, c0, c1 = nz_rows[0], nz_rows[-1], nz_cols[0], nz_cols[-1]
    box = [row[c0:c1 + 1] for row in vals[r0:r1 + 1]]
    ox, oy = canvas_left + c0, canvas_bottom + (n - 1 - r1)
    box, ox, oy = fit_into_cell(rid, size, box, ox, oy, int(adv_px),
                                ref['line_height'] - ref['base_line'], -ref['base_line'])
    return (ref['adv_w'], len(box[0]), len(box), ox, oy, box)


FIT_LOG = []


def fit_into_cell(rid, size, box, ox, oy, adv, top, bottom):
    """Keep the glyph inside [0, adv) x [bottom, top): the area of a label holding it.

    A few icons are drawn a hair beyond their view box, and integer placement adds the
    rest: they would stand up to one pixel outside, where LVGL clips the label anyway.
    Shift inward where the cell has room; where it has none, drop the outermost row or
    column ourselves, so the font shows exactly what the panel will show. Dropping more
    than anti-aliasing fringe is reported - that would be real shape lost."""
    bw, bh = len(box[0]), len(box)
    shifted, dropped = 0, 0
    # horizontal: shift first, then clip what still does not fit
    if ox < 0 and ox + bw < adv:
        s = min(-ox, adv - (ox + bw)); ox += s; shifted += s
    elif ox + bw > adv and ox > 0:
        s = min(ox + bw - adv, ox); ox -= s; shifted += s
    while ox < 0 and len(box[0]) > 1:
        dropped = max(dropped, max(r[0] for r in box)); box = [r[1:] for r in box]; ox += 1
    while ox + len(box[0]) > adv and len(box[0]) > 1:
        dropped = max(dropped, max(r[-1] for r in box)); box = [r[:-1] for r in box]
    # vertical: oy is the bottom edge above the baseline, box[0] is the top row
    bh = len(box)
    if oy < bottom and oy + bh < top:
        s = min(bottom - oy, top - (oy + bh)); oy += s; shifted += s
    elif oy + bh > top and oy > bottom:
        s = min(oy + bh - top, oy - bottom); oy -= s; shifted += s
    while oy < bottom and len(box) > 1:
        dropped = max(dropped, max(box[-1])); box = box[:-1]; oy += 1
    while oy + len(box) > top and len(box) > 1:
        dropped = max(dropped, max(box[0])); box = box[1:]
    if shifted or dropped:
        FIT_LOG.append((size, rid, shifted, dropped))
    return box, ox, oy


def pack4(rows):
    out, acc, nbits = bytearray(), 0, 0
    for row in rows:
        for v in row:
            acc = (acc << 4) | v
            nbits += 4
            while nbits >= 8:
                nbits -= 8
                out.append((acc >> nbits) & 0xFF)
    if nbits:
        out.append((acc << (8 - nbits)) & 0xFF)
    return bytes(out)


# ── emitting C ───────────────────────────────────────────────────────────────

def size_guard(size):
    small, big = size in SIZES_SMALL, size in SIZES_BIG
    if small and big:
        return None
    return '!defined(BOARD_PANEL_1024X600)' if small else 'defined(BOARD_PANEL_1024X600)'


# The CC BY 4.0 change statements (section 3(a)(1)(B)). ONE wording each, used
# verbatim by THIRD-PARTY-NOTICES.md, src/display/LicenseText.h and OB_ATTRIB in
# data/index.html as well - change them everywhere or nowhere.
CHANGES_FONT = 'rasterised into 4-bpp bitmap fonts and reduced to one colour'
CHANGES_WEB = 'reduced to one colour (currentColor), coordinates rounded'


def licence_block(src):
    return [
        ' * LICENCE - this file holds licensed artwork and is NOT under NauticPinnace\'s',
        ' * MIT licence:',
        ' *   "%s" by %s' % (src.get('title', 'OpenBridge Icon Pack'), src.get('author', 'OpenBridge')),
        ' *   %s' % src.get('url', ''),
        ' *   %s, %s' % (src.get('licence', 'CC BY 4.0'), src.get('licenceUrl', '')),
        ' *   Provided as is, without warranties of any kind (Section 5 of the licence).',
        ' *   Licence text: LICENSES/CC-BY-4.0.txt. Exported from Figma on %s.'
        % src.get('exportDate', '?'),
        ' * Changes: %s.' % CHANGES_FONT,
        ' * Icons whose id ends in -google are based on Google Material Icons, (c) Google',
        ' *   LLC, Apache License 2.0 (LICENSES/Apache-2.0.txt). Icons whose id ends in -iec',
        ' *   are OpenBridge redrawings of IEC 62288 symbols; no rights of the IEC are granted.',
        ' * NauticPinnace is not affiliated with or endorsed by OpenBridge.',
        ' * Redistribute this file only together with that notice.',
    ]


def emit_font(size, ref, glyphs, src):
    sym = 'ob_icons_%d' % size
    guard = size_guard(size)
    bitmap, dscs = bytearray(), []
    for (macro, rid), (adv, bw, bh, ox, oy, rows) in zip(PANEL_ICONS, glyphs):
        dscs.append((len(bitmap), adv, bw, bh, ox, oy, rid))
        bitmap += pack4(rows)
    L = ['/* GENERATED by tools/gen_icons.py from tools/icons/openbridge-map.json and the Figma',
         ' * export of the "OpenBridge Icon Pack" - DO NOT EDIT; run  python tools/gen_icons.py',
         ' * OpenBridge icon trial: this file belongs to the trial (see ICONS-TRIAL.md).',
         ' *',
         ' * Size: %d px   Bpp: 4   Glyphs: %d   Code points: U+%04X..U+%04X (Private Use Area)'
         % (size, len(dscs), PUA_BASE, PUA_BASE + len(dscs) - 1),
         ' *'] + licence_block(src) + [' */']
    L += ['#ifdef LV_LVGL_H_INCLUDE_SIMPLE', '    #include "lvgl.h"', '#else',
          '    #include "lvgl/lvgl.h"', '#endif', '']
    if guard:
        L += ['/* Only the board(s) whose font roles use this size. */', '#if %s' % guard, '']
    L.append('static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {')
    for i in range(0, len(bitmap), 16):
        L.append('    ' + ', '.join('0x%02x' % b for b in bitmap[i:i + 16]) + ',')
    L += ['};', '',
          'static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {',
          '    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,']
    for i, (bi, adv, bw, bh, ox, oy, rid) in enumerate(dscs):
        L.append('    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, '
                 '.ofs_y = %d}, /* U+%04X %s */' % (bi, adv, bw, bh, ox, oy, PUA_BASE + i, rid))
    L += ['};', '',
          'static const lv_font_fmt_txt_cmap_t cmaps[] = {',
          '    {',
          '        .range_start = %d, .range_length = %d, .glyph_id_start = 1,'
          % (PUA_BASE, len(dscs)),
          '        .unicode_list = NULL, .glyph_id_ofs_list = NULL,',
          '        .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY',
          '    }',
          '};', '',
          'static lv_font_fmt_txt_glyph_cache_t cache;',
          'static const lv_font_fmt_txt_dsc_t font_dsc = {',
          '    .glyph_bitmap = glyph_bitmap,',
          '    .glyph_dsc = glyph_dsc,',
          '    .cmaps = cmaps,',
          '    .kern_dsc = NULL,',
          '    .kern_scale = 0,',
          '    .cmap_num = 1,',
          '    .bpp = 4,',
          '    .kern_classes = 0,',
          '    .bitmap_format = 0,',
          '    .cache = &cache',
          '};', '',
          '/* Line metrics copied from Montserrat %d: the font only ever serves as a fallback' % size,
          ' * behind it, and LVGL positions a fallback glyph on the MAIN font\'s baseline. */',
          'const lv_font_t %s = {' % sym,
          '    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,',
          '    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,',
          '    .line_height = %d,' % ref['line_height'],
          '    .base_line = %d,' % ref['base_line'],
          '    .subpx = LV_FONT_SUBPX_NONE,',
          '    .underline_position = %d,' % (-(size // 10)),
          '    .underline_thickness = %d,' % max(1, size // 24),
          '    .dsc = &font_dsc,',
          '    .fallback = NULL,',
          '    .user_data = NULL,',
          '};', '']
    if guard:
        L += ['#endif /* %s */' % guard, '']
    return '\n'.join(L), len(bitmap)


def emit_header(sizes):
    L = ['/* GENERATED by tools/gen_icons.py - DO NOT EDIT; run  python tools/gen_icons.py',
         ' * OpenBridge icon trial: this file belongs to the trial (see ICONS-TRIAL.md).',
         ' *',
         ' * Code points of the OpenBridge icons in the Private Use Area, as UTF-8 string',
         ' * literals, and the icon fonts. This header holds no artwork (MIT); the glyphs are',
         ' * in ob_icons_<px>.c (CC BY 4.0).',
         ' *',
         ' * Each macro is ONE string literal of three \\xNN escapes. Hex escapes are greedy,',
         ' * so never glue a hex digit directly onto one inside the same literal: write',
         ' * OB_ICON_ALARM " 5 m" (two literals), never "\\xEE\\x80\\x96" "5" merged by hand.',
         ' */',
         '#pragma once',
         '#ifdef LV_LVGL_H_INCLUDE_SIMPLE',
         '    #include "lvgl.h"',
         '#else',
         '    #include "lvgl/lvgl.h"',
         '#endif',
         '']
    for i, (macro, rid) in enumerate(PANEL_ICONS):
        b = chr(PUA_BASE + i).encode('utf-8')
        lit = ''.join('\\x%02X' % c for c in b)
        L.append('#define OB_ICON_%-14s "%s"   /* U+%04X %s */' % (macro, lit, PUA_BASE + i, rid))
    L += ['', '#define OB_ICON_COUNT %d' % len(PANEL_ICONS), '',
          '/* Icon font sizes compiled into this board (pixel sizes of the font roles). */',
          '#if defined(BOARD_PANEL_1024X600)',
          '#define OB_ICON_SIZES(X) ' + ' '.join('X(%d)' % s for s in SIZES_BIG),
          '#else',
          '#define OB_ICON_SIZES(X) ' + ' '.join('X(%d)' % s for s in SIZES_SMALL),
          '#endif', '']
    for s in sizes:
        L.append('LV_FONT_DECLARE(ob_icons_%d)' % s)
    L.append('')
    return '\n'.join(L)


# ── the web sprite ───────────────────────────────────────────────────────────

def sprite_block(src, icons):
    attribution = ('Icons: "%s" by %s, %s, %s %s, exported %s. Changes: %s. '
                   'Icons whose id ends in -google are based on Google Material Icons (Google '
                   'LLC, Apache-2.0); icons whose id ends in -iec are OpenBridge redrawings of '
                   'IEC 62288 symbols (no IEC rights granted). Not affiliated with or endorsed '
                   'by OpenBridge. OpenBridge icon trial.'
                   % (src.get('title', 'OpenBridge Icon Pack'), src.get('author', 'OpenBridge'),
                      src.get('url', ''), src.get('licence', 'CC BY 4.0'),
                      src.get('licenceUrl', ''), src.get('exportDate', '?'), CHANGES_WEB))
    if '--' in attribution:
        raise SystemExit('attribution text must not contain "--" (HTML comment)')
    lines = [SPRITE_BEGIN,
             '<svg xmlns="http://www.w3.org/2000/svg" id="%s" width="0" height="0" '
             'style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true" '
             'focusable="false">' % SPRITE_ELEMENT_ID,
             '<!-- %s -->' % attribution]
    for rid in WEB_ICONS:
        vb, kids = icons[rid]
        lines.append('<symbol id="%s%s" viewBox="%s">%s</symbol>'
                     % (SYMBOL_PREFIX, rid, vb, ''.join(serialise(k) for k in kids)))
    lines += ['</svg>', SPRITE_END]
    text = '\n'.join(lines)
    if any(ord(c) > 127 for c in text):
        raise SystemExit('sprite must be plain ASCII')
    return text


def splice_sprite(html, block):
    a, b = html.find(SPRITE_BEGIN), html.find(SPRITE_END)
    if a < 0 or b < 0 or b < a:
        raise SystemExit('ERROR: data/index.html has no sprite markers. Put the two lines\n  %s\n'
                         '  %s\nright after <body>, then run again.' % (SPRITE_BEGIN, SPRITE_END))
    return html[:a] + block + html[b + len(SPRITE_END):]


# ── preview ──────────────────────────────────────────────────────────────────

def write_preview(path, per_size):
    from PIL import Image, ImageDraw
    sizes = sorted(per_size)
    cell = max(sizes) + 16
    img = Image.new('RGB', (len(PANEL_ICONS) * cell + 120, len(sizes) * cell + 8), (255, 255, 255))
    dr = ImageDraw.Draw(img)
    for si, size in enumerate(sizes):
        y0 = 4 + si * cell
        dr.text((4, y0 + cell // 2 - 6), '%d px' % size, fill=(0, 0, 0))
        ref, glyphs = per_size[size]
        base = y0 + cell - 8                           # baseline of this row
        for gi, (adv, bw, bh, ox, oy, rows) in enumerate(glyphs):
            x0 = 120 + gi * cell
            dr.rectangle([x0, base - ref['line_height'] + ref['base_line'],
                          x0 + adv // 16 - 1, base + ref['base_line'] - 1], outline=(220, 220, 255))
            for r, row in enumerate(rows):
                for c, v in enumerate(row):
                    if v:
                        g = 255 - v * 17
                        img.putpixel((x0 + ox + c, base - oy - bh + r), (g, g, g))
    img.save(path)


# ── main ─────────────────────────────────────────────────────────────────────

def main(argv=None):
    ap = argparse.ArgumentParser(description='OpenBridge icon trial: build the icon fonts and '
                                             'the web sprite.')
    ap.add_argument('--export', help='Figma export JSON (outside the repo); default: '
                                     '$OPENBRIDGE_EXPORT or ../Provenance/OpenBridge/')
    ap.add_argument('--map', default=DEFAULT_MAP, help='shared mapping file')
    ap.add_argument('--check', action='store_true',
                    help='do not write; exit 1 if any output differs from what would be written')
    ap.add_argument('--preview', metavar='PNG', help='also write a contact sheet of every glyph')
    ap.add_argument('--verbose', action='store_true', help='also print the per-icon notes')
    args = ap.parse_args(argv)
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

    export, tried = find_export(args.export)
    if not export:
        print('ERROR: Figma export not found. Tried:\n  ' + '\n  '.join(tried))
        return 2

    rep = Report()
    panel_ids = [rid for _m, rid in PANEL_ICONS]
    mp, icons = load_icons(export, args.map, panel_ids + WEB_ICONS, rep)
    shapes = {}
    for rid in panel_ids:
        if rid in icons:
            try:
                shapes[rid] = icon_shapes(rid, icons[rid][1])
            except IconError as ex_:
                rep.error(rid, str(ex_))
    if args.verbose:
        for n in rep.notes:
            print('  note: ' + n)
    for w in rep.warnings:
        print('WARNING: ' + w)
    for e in rep.errors:
        print('ERROR: ' + e)
    if rep.errors:
        print('%d error(s): nothing written.' % len(rep.errors))
        return 1
    src = mp.get('source', {})

    outputs = collections.OrderedDict()
    per_size, total = {}, {}
    sizes = sorted(set(SIZES_SMALL) | set(SIZES_BIG))
    for size in sizes:
        ref = montserrat_reference(size)
        glyphs = []
        for rid in panel_ids:
            vb = [float(v) for v in icons[rid][0].split()]
            try:
                glyphs.append(make_glyph(rid, vb, shapes[rid], size, ref))
            except IconError as ex_:
                print('ERROR: %s: %s' % (rid, ex_))
                return 1
        text, nbytes = emit_font(size, ref, glyphs, src)
        outputs[os.path.join(FONT_DIR, 'ob_icons_%d.c' % size)] = text
        per_size[size] = (ref, glyphs)
        total[size] = nbytes
    outputs[HEADER_OUT] = emit_header(sizes)
    with open(INDEX_HTML, encoding='utf-8') as f:
        html = f.read()
    outputs[INDEX_HTML] = splice_sprite(html, sprite_block(src, icons))

    for size, rid, shifted, dropped in FIT_LOG:
        msg = '%s at %d px: kept inside its cell (shifted %d px, dropped edge up to %d/15)'             % (rid, size, shifted, dropped)
        if dropped >= 15:
            print('WARNING: ' + msg + ' - a SOLID pixel was cut off')
        elif args.verbose:
            print('  note: ' + msg)
    print('icons: %d panel, %d web; sizes: %s' % (len(PANEL_ICONS), len(WEB_ICONS),
                                                  ' '.join(str(s) for s in sizes)))
    for label, set_ in (('4-inch', SIZES_SMALL), ('1024x600', SIZES_BIG)):
        print('glyph data %-9s %6d bytes (%s)' % (label, sum(total[s] for s in set_),
                                                ' + '.join('%d' % total[s] for s in set_)))

    stale = []
    for path, text in outputs.items():
        data = text.encode('utf-8')
        try:
            with open(path, 'rb') as f:
                old = f.read().replace(b'\r\n', b'\n')
        except OSError:
            old = None
        if old == data:
            continue
        if args.check:
            stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'wb') as f:
                f.write(data)
            print('written: %s' % os.path.relpath(path, REPO))
    if args.preview:
        write_preview(args.preview, per_size)
        print('preview: %s' % args.preview)
    if args.check:
        for p in stale:
            print('STALE: %s' % os.path.relpath(p, REPO))
        print('up to date' if not stale else '%d file(s) stale' % len(stale))
        return 1 if stale else 0
    return 0


if __name__ == '__main__':
    sys.exit(main())
