#!/usr/bin/env python3
"""
gen_logo_mark.py - render the NauticPi brand mark (pi glyph over a wave) as
two LVGL ALPHA_8BIT images: src/display/logo_mark.c

The geometry is lifted 1:1 from the NauticPi MFD page (MfdHtml.cs, the
<svg viewBox="0 0 660 200"> header logo): pi = three strokes at width 15
inside a translate(18,14) scale(0.85) group, wave = one cubic pair at
width 11. Two separate alpha layers so the firmware can recolor them
independently (pi -> theme text color, wave -> theme accent) and the mark
stays crisp in light/dark/night.

Usage:  python gen_logo_mark.py            (writes ../src/display/logo_mark.c)
"""
import pathlib

from PIL import Image, ImageDraw

# Two native renders: 72x46 for the home-overlay header, 54x35 (75%) for the
# rail - a native render stays crisper than lv_img_set_zoom on an alpha image.
SIZES = [("", 72, 46), ("_sm", 54, 35)]
W, H = 72, 46          # active size (set per loop below)
S = 8                  # supersampling factor

# Mark bounding region in SVG units (with stroke radius margins).
X0, Y0, SPAN = 12.0, 61.0, 186.0
SCALE = W / SPAN


def pt(x, y):
    return ((x - X0) * SCALE * S, (y - Y0) * SCALE * S)


def stroke(draw, pts, width_svg):
    w = width_svg * SCALE * S
    r = w / 2
    for i in range(len(pts) - 1):
        draw.line([pts[i], pts[i + 1]], fill=255, width=round(w))
    for x, y in pts:                       # round caps/joints
        draw.ellipse([x - r, y - r, x + r, y + r], fill=255)


def bez(p0, c1, c2, p3, n=48):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**3 * p0[0] + 3 * u**2 * t * c1[0] + 3 * u * t**2 * c2[0] + t**3 * p3[0]
        y = u**3 * p0[1] + 3 * u**2 * t * c1[1] + 3 * u * t**2 * c2[1] + t**3 * p3[1]
        out.append((x, y))
    return out


def quad(p0, c, p1, n=32):
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        x = u**2 * p0[0] + 2 * u * t * c[0] + t**2 * p1[0]
        y = u**2 * p0[1] + 2 * u * t * c[1] + t**2 * p1[1]
        out.append((x, y))
    return out


def g(x, y):                       # the pi group: translate(18,14) scale(0.85)
    return (18 + 0.85 * x, 14 + 0.85 * y)


def render_layer(paths):
    img = Image.new("L", (W * S, H * S), 0)
    d = ImageDraw.Draw(img)
    for pts, w_svg in paths:
        stroke(d, [pt(*p) for p in pts], w_svg)
    return img.resize((W, H), Image.LANCZOS)


PI_W = 15 * 0.85


def build_layers():
    pi = render_layer([
        ([g(40, 66), g(160, 66)], PI_W),                                   # bar
        ([g(67, 66), g(67, 138)], PI_W),                                   # left leg
        ([g(130, 66)] + [g(*p) for p in quad((130, 66), (130, 125), (130, 125), 2)]
         + [g(*p) for p in quad((130, 125), (130, 140), (147, 140))], PI_W),  # right leg + curl
    ])
    wave = render_layer([
        (bez((20, 150), (50, 130), (82, 130), (112, 150))
         + bez((112, 150), (142, 170), (162, 170), (190, 150)), 11),
    ])
    return pi, wave


def emit(name, img):
    w, h = img.size
    data = img.tobytes()
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    body = "\n".join(lines)
    return (f"static const uint8_t {name}_map[] = {{\n{body}\n}};\n\n"
            f"const lv_img_dsc_t {name} = {{\n"
            f"    .header.cf = LV_IMG_CF_ALPHA_8BIT,\n"
            f"    .header.always_zero = 0,\n"
            f"    .header.reserved = 0,\n"
            f"    .header.w = {w},\n"
            f"    .header.h = {h},\n"
            f"    .data_size = {w * h},\n"
            f"    .data = {name}_map,\n"
            f"}};\n")


parts = []
for suffix, w_out, h_out in SIZES:
    W, H = w_out, h_out
    SCALE = W / SPAN
    pi_layer, wave_layer = build_layers()
    parts.append(emit(f"logo_mark_pi{suffix}", pi_layer))
    parts.append(emit(f"logo_mark_wave{suffix}", wave_layer))

out = pathlib.Path(__file__).resolve().parent.parent / "src" / "display" / "logo_mark.c"
out.write_text(
    "// AUTO-GENERATED by tools/gen_logo_mark.py - do not edit by hand.\n"
    "// NauticPi brand mark as two recolorable alpha layers (pi + wave) in two\n"
    "// sizes (72x46 header, 54x35 rail); geometry identical to the NauticPi\n"
    "// MFD header logo.\n"
    "#include <lvgl.h>\n\n"
    + "\n".join(parts),
    encoding="ascii",
)
print(f"wrote {out}: " + ", ".join(f"logo_mark_*{s or ''} {w}x{h}" for s, w, h in SIZES))
