# lvgl_font.py — shared emitter for LVGL v8 font C files (4bpp, uncompressed).
#
# Output format matches lv_font_conv's "lvgl" target:
#   - 4 bpp, MSB-first continuous bitstream per glyph, each glyph byte-aligned
#   - SPARSE_TINY cmap (sorted unicode list)
#
# Used by gen_depth_font.py (large numeric hero font) and
# gen_latin_supplement.py (umlaut fallback fonts).
import freetype


def render_font(ttf, size, chars):
    """Rasterise `chars` from `ttf` at `size` px. Returns (bitmap, glyphs, metrics)."""
    chars = sorted(set(chars), key=lambda c: ord(c))

    face = freetype.Face(ttf)
    face.set_pixel_sizes(0, size)

    # Font-level vertical metrics (26.6 fixed -> px)
    ascender  = face.size.ascender  >> 6
    descender = face.size.descender >> 6           # negative
    line_height = ascender - descender
    base_line   = -descender                       # px below baseline

    bitmap = bytearray()       # concatenated, byte-aligned per glyph
    glyphs = []                # (codepoint, adv_w, box_w, box_h, ofs_x, ofs_y, bitmap_index)

    for ch in chars:
        face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g  = face.glyph
        bm = g.bitmap
        w, h, pitch = bm.width, bm.rows, bm.pitch
        adv_px = g.advance.x / 64.0
        adv_w  = int(round(adv_px * 16))           # 8.4 fixed
        ofs_x  = g.bitmap_left
        ofs_y  = g.bitmap_top - h                  # bottom of box, measured up from baseline
        idx    = len(bitmap)

        # Pack 4bpp MSB-first, row-major, continuous within the glyph.
        acc = 0; nbits = 0
        for row in range(h):
            base = row * pitch
            for col in range(w):
                gray = bm.buffer[base + col]
                v4 = (gray * 15 + 127) // 255      # 0..15, rounded
                acc = (acc << 4) | v4
                nbits += 4
                while nbits >= 8:
                    nbits -= 8
                    bitmap.append((acc >> nbits) & 0xFF)
        if nbits:                                  # flush + byte-align glyph
            bitmap.append((acc << (8 - nbits)) & 0xFF)

        glyphs.append((ord(ch), adv_w, w, h, ofs_x, ofs_y, idx))

    return bitmap, glyphs, (line_height, base_line, ascender, descender), chars


def emit_c(ttf, size, chars, symbol, generator):
    """Return the complete C source for an LVGL v8 font."""
    bitmap, glyphs, metrics, chars = render_font(ttf, size, chars)
    line_height, base_line, ascender, descender = metrics

    range_start = ord(chars[0])
    rcp = [ord(c) - range_start for c in chars]
    range_length = rcp[-1] + 1

    def hexrow(data, per=12):
        out_lines, line = [], []
        for b in data:
            line.append("0x%02x" % b)
            if len(line) == per:
                out_lines.append("    " + ", ".join(line) + ",")
                line = []
        if line:
            out_lines.append("    " + ", ".join(line) + ",")
        return "\n".join(out_lines) if out_lines else "    0x00,"

    src_name = ttf.split('/')[-1].split('\\')[-1]
    L = []
    L.append("/* Generated by tools/%s - DO NOT EDIT BY HAND." % generator)
    L.append(" * Font: %s   Size: %d px   Bpp: 4   Glyphs: %s" %
             (src_name, size, "".join(chars).replace(" ", "<sp>")))
    L.append(" *")
    # The SIL OFL explicitly treats a format conversion as a "Modified
    # Version" - so this generated file is itself Font Software and must
    # carry the copyright notice and a licence reference.
    if "montserrat" in src_name.lower():
        L.append(" * ---------------------------------------------------------------------")
        L.append(" * Derived from the Montserrat typeface.")
        L.append(" *   Copyright 2011 The Montserrat Project Authors")
        L.append(" *   https://github.com/JulietaUla/Montserrat")
        L.append(" *")
        L.append(" * Licensed under the SIL Open Font License, Version 1.1.")
        L.append(" *   https://scripts.sil.org/OFL")
        L.append(" *")
        L.append(" * The OFL treats a conversion to another format as a Modified Version,")
        L.append(" * so this file is itself Font Software and stays under the OFL. It may")
        L.append(" * be redistributed only together with this notice and the licence text")
        L.append(" * (see THIRD-PARTY-NOTICES.md), and not under the reserved name")
        L.append(" * \"Montserrat\".")
        L.append(" * ---------------------------------------------------------------------")
    else:
        L.append(" * NOTE: check the source font's licence before redistributing this file;")
        L.append(" * a format conversion is usually still governed by it.")
    L.append(" */")
    L.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
    L.append('    #include "lvgl.h"')
    L.append("#else")
    L.append('    #include "lvgl/lvgl.h"')
    L.append("#endif")
    L.append("")
    L.append("#ifndef %s" % symbol.upper())
    L.append("#define %s 1" % symbol.upper())
    L.append("#endif")
    L.append("")
    L.append("#if %s" % symbol.upper())
    L.append("")
    L.append("/*-----------------\n *    BITMAPS\n *----------------*/")
    L.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    L.append(hexrow(bitmap))
    L.append("};")
    L.append("")
    L.append("/*---------------------\n *  GLYPH DESCRIPTION\n *--------------------*/")
    L.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    L.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,")
    for (cp, adv_w, w, h, ox, oy, idx) in glyphs:
        L.append("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d}, /* U+%04X '%s' */"
                 % (idx, adv_w, w, h, ox, oy, cp, (chr(cp) if cp != 0x20 else ' ')))
    L.append("};")
    L.append("")
    L.append("/*---------------------\n *  CHARACTER MAPPING\n *--------------------*/")
    L.append("static const uint16_t unicode_list_0[] = {")
    L.append("    " + ", ".join(str(v) for v in rcp))
    L.append("};")
    L.append("")
    L.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    L.append("    {")
    L.append("        .range_start = %d, .range_length = %d, .glyph_id_start = 1," % (range_start, range_length))
    L.append("        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL,")
    L.append("        .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY" % len(rcp))
    L.append("    }")
    L.append("};")
    L.append("")
    L.append("/*--------------------\n *  ALL CUSTOM DATA\n *--------------------*/")
    L.append("#if LV_VERSION_CHECK(8, 0, 0)")
    L.append("static lv_font_fmt_txt_glyph_cache_t cache;")
    L.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#else")
    L.append("static lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#endif")
    L.append("    .glyph_bitmap = glyph_bitmap,")
    L.append("    .glyph_dsc = glyph_dsc,")
    L.append("    .cmaps = cmaps,")
    L.append("    .kern_dsc = NULL,")
    L.append("    .kern_scale = 0,")
    L.append("    .cmap_num = 1,")
    L.append("    .bpp = 4,")
    L.append("    .kern_classes = 0,")
    L.append("    .bitmap_format = 0,")
    L.append("#if LV_VERSION_CHECK(8, 0, 0)")
    L.append("    .cache = &cache")
    L.append("#endif")
    L.append("};")
    L.append("")
    L.append("/*-----------------\n *  PUBLIC FONT\n *----------------*/")
    L.append("#if LV_VERSION_CHECK(8, 0, 0)")
    L.append("const lv_font_t %s = {" % symbol)
    L.append("#else")
    L.append("lv_font_t %s = {" % symbol)
    L.append("#endif")
    L.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    L.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    L.append("    .line_height = %d," % line_height)
    L.append("    .base_line = %d," % base_line)
    L.append("    .subpx = LV_FONT_SUBPX_NONE,")
    L.append("    .underline_position = %d," % (-(size // 10)))
    L.append("    .underline_thickness = %d," % max(1, size // 24))
    L.append("    .dsc = &font_dsc,")
    L.append("    .fallback = NULL,")
    L.append("    .user_data = NULL,")
    L.append("};")
    L.append("")
    L.append("#endif /* %s */" % symbol.upper())
    L.append("")

    stats = dict(glyphs=len(glyphs), bitmap_bytes=len(bitmap),
                 line_height=line_height, base_line=base_line,
                 ascender=ascender, descender=descender)
    return "\n".join(L), stats
